-- SEED: week-1 matchup + pick pools (roster 5 = dachhack/Happy Campers vs roster 1).
insert into matchup (league_id, week, home_roster_id, away_roster_id, status, lock_at)
select (select id from league where sleeper_league_id='1181483840740397056' and season='2026'), 1, 5, 1, 'scheduled', '2026-09-05T00:20:00Z'
on conflict (league_id, week, home_roster_id, away_roster_id) do update set lock_at=excluded.lock_at, status='scheduled';

insert into sleeper_lineup (league_id, week, roster_id, starters_json)
select (select id from league where sleeper_league_id='1181483840740397056' and season='2026'), v.week, v.roster_id, v.starters
from (values
  (1, 5, '[{"slug": "cade-stover", "full": "Cade Stover", "pos": "TE"}, {"slug": "jordan-addison", "full": "Jordan Addison", "pos": "WR"}, {"slug": "brock-bowers", "full": "Brock Bowers", "pos": "TE"}, {"slug": "josh-jacobs", "full": "Josh Jacobs", "pos": "RB"}, {"slug": "jalen-milroe", "full": "Jalen Milroe", "pos": "QB"}, {"slug": "alvin-kamara", "full": "Alvin Kamara", "pos": "RB"}, {"slug": "caleb-williams", "full": "Caleb Williams", "pos": "QB"}, {"slug": "michael-mayer", "full": "Michael Mayer", "pos": "TE"}, {"slug": "wandale-robinson", "full": "Wan''Dale Robinson", "pos": "WR"}, {"slug": "joe-mixon", "full": "Joe Mixon", "pos": "RB"}, {"slug": "christian-kirk", "full": "Christian Kirk", "pos": "WR"}, {"slug": "terry-mclaurin", "full": "Terry McLaurin", "pos": "WR"}, {"slug": "travis-etienne", "full": "Travis Etienne", "pos": "RB"}, {"slug": "cole-kmet", "full": "Cole Kmet", "pos": "TE"}, {"slug": "jaylin-noel", "full": "Jaylin Noel", "pos": "WR"}, {"slug": "russell-wilson", "full": "Russell Wilson", "pos": "QB"}, {"slug": "george-kittle", "full": "George Kittle", "pos": "TE"}, {"slug": "cedric-tillman", "full": "Cedric Tillman", "pos": "WR"}, {"slug": "jack-bech", "full": "Jack Bech", "pos": "WR"}, {"slug": "devonta-smith", "full": "DeVonta Smith", "pos": "WR"}, {"slug": "tyrone-tracy", "full": "Tyrone Tracy", "pos": "RB"}, {"slug": "dallas-goedert", "full": "Dallas Goedert", "pos": "TE"}, {"slug": "trevor-lawrence", "full": "Trevor Lawrence", "pos": "QB"}, {"slug": "jaylin-lane", "full": "Jaylin Lane", "pos": "WR"}, {"slug": "christian-mccaffrey", "full": "Christian McCaffrey", "pos": "RB"}, {"slug": "chimere-dike", "full": "Chimere Dike", "pos": "WR"}, {"slug": "george-pickens", "full": "George Pickens", "pos": "WR"}, {"slug": "christian-watson", "full": "Christian Watson", "pos": "WR"}, {"slug": "baker-mayfield", "full": "Baker Mayfield", "pos": "QB"}, {"slug": "davante-adams", "full": "Davante Adams", "pos": "WR"}, {"slug": "jalen-mcmillan", "full": "Jalen McMillan", "pos": "WR"}, {"slug": "joe-milton", "full": "Joe Milton", "pos": "QB"}, {"slug": "dak-prescott", "full": "Dak Prescott", "pos": "QB"}, {"slug": "kyle-pitts", "full": "Kyle Pitts", "pos": "TE"}]'::jsonb),
  (1, 1, '[{"slug": "kyler-murray", "full": "Kyler Murray", "pos": "QB"}, {"slug": "jayden-daniels", "full": "Jayden Daniels", "pos": "QB"}, {"slug": "darren-waller", "full": "Darren Waller", "pos": "TE"}, {"slug": "marcus-mariota", "full": "Marcus Mariota", "pos": "QB"}, {"slug": "cj-stroud", "full": "C.J. Stroud", "pos": "QB"}, {"slug": "jacoby-brissett", "full": "Jacoby Brissett", "pos": "QB"}, {"slug": "lequint-allen", "full": "LeQuint Allen", "pos": "RB"}, {"slug": "chris-olave", "full": "Chris Olave", "pos": "WR"}, {"slug": "adonai-mitchell", "full": "Adonai Mitchell", "pos": "WR"}, {"slug": "quentin-johnston", "full": "Quentin Johnston", "pos": "WR"}, {"slug": "chase-brown", "full": "Chase Brown", "pos": "RB"}, {"slug": "quinn-ewers", "full": "Quinn Ewers", "pos": "QB"}, {"slug": "xavier-legette", "full": "Xavier Legette", "pos": "WR"}, {"slug": "pat-freiermuth", "full": "Pat Freiermuth", "pos": "TE"}, {"slug": "rhamondre-stevenson", "full": "Rhamondre Stevenson", "pos": "RB"}, {"slug": "tank-bigsby", "full": "Tank Bigsby", "pos": "RB"}, {"slug": "raheim-sanders", "full": "Raheim Sanders", "pos": "RB"}, {"slug": "brian-thomas", "full": "Brian Thomas", "pos": "WR"}, {"slug": "pat-bryant", "full": "Pat Bryant", "pos": "WR"}, {"slug": "konata-mumpfield", "full": "Konata Mumpfield", "pos": "WR"}, {"slug": "arian-smith", "full": "Arian Smith", "pos": "WR"}, {"slug": "anthony-richardson", "full": "Anthony Richardson", "pos": "QB"}, {"slug": "malik-nabers", "full": "Malik Nabers", "pos": "WR"}, {"slug": "bijan-robinson", "full": "Bijan Robinson", "pos": "RB"}, {"slug": "devon-achane", "full": "De''Von Achane", "pos": "RB"}, {"slug": "jaxson-dart", "full": "Jaxson Dart", "pos": "QB"}, {"slug": "puka-nacua", "full": "Puka Nacua", "pos": "WR"}, {"slug": "terrance-ferguson", "full": "Terrance Ferguson", "pos": "TE"}, {"slug": "nico-collins", "full": "Nico Collins", "pos": "WR"}, {"slug": "sam-laporta", "full": "Sam LaPorta", "pos": "TE"}, {"slug": "isiah-pacheco", "full": "Isiah Pacheco", "pos": "RB"}, {"slug": "jauan-jennings", "full": "Jauan Jennings", "pos": "WR"}, {"slug": "davis-mills", "full": "Davis Mills", "pos": "QB"}, {"slug": "jake-tonges", "full": "Jake Tonges", "pos": "TE"}, {"slug": "parker-washington", "full": "Parker Washington", "pos": "WR"}]'::jsonb)
) as v(week, roster_id, starters)
on conflict (league_id, week, roster_id) do update set starters_json=excluded.starters_json;
