// Generates src/data/headshots.ts: player slug -> ESPN headshot URL.
//
// Source of truth:
//   - scripts/pbp/crosswalk.json  (slug -> { gsis, pos, name, ... })
//   - nflverse players.csv        (gsis_id -> espn_id)
//
// The nflverse file is downloaded on demand (cached at scripts/pbp/players.csv,
// which is gitignored). Existing entries in headshots.ts are preserved so we
// never lose a hand-verified or previously-resolved headshot.
//
// Usage: node scripts/pbp/genHeadshots.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");

const CROSSWALK = path.join(__dirname, "crosswalk.json");
const OUT = path.join(ROOT, "src", "data", "headshots.ts");

// nflverse sources for gsis_id -> espn_id, tried in order. players.csv is the
// canonical components file; the weekly roster file is a fallback that tends to
// carry espn_ids for recent rookies sooner than the components file.
const SOURCES = [
  {
    file: path.join(__dirname, "players.csv"),
    url: "https://github.com/nflverse/nflverse-data/releases/download/players_components/players.csv",
  },
  {
    file: path.join(__dirname, "roster_2025.csv"),
    url: "https://github.com/nflverse/nflverse-data/releases/download/rosters/roster_2025.csv",
  },
];

const headshotUrl = (espnId) =>
  `https://a.espncdn.com/i/headshots/nfl/players/full/${espnId}.png`;

// Minimal CSV parser that handles quoted fields containing commas/quotes.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (c === "\r") {
      // ignore
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

async function ensureCsv(source) {
  if (fs.existsSync(source.file)) return;
  console.log(`Downloading ${path.basename(source.file)} from nflverse...`);
  const res = await fetch(source.url);
  if (!res.ok)
    throw new Error(`Failed to download ${source.url}: ${res.status}`);
  fs.writeFileSync(source.file, await res.text());
}

// Build a gsis_id -> espn_id map, layering sources so earlier ones win and
// later ones only fill gaps.
function buildGsisToEspn() {
  const map = new Map();
  for (const source of SOURCES) {
    const rows = parseCsv(fs.readFileSync(source.file, "utf8"));
    const header = rows[0];
    const gsisIdx = header.indexOf("gsis_id");
    const espnIdx = header.indexOf("espn_id");
    if (gsisIdx < 0 || espnIdx < 0)
      throw new Error(`${source.file} missing gsis_id/espn_id columns`);
    for (let i = 1; i < rows.length; i++) {
      const gsis = rows[i][gsisIdx];
      const espn = rows[i][espnIdx];
      if (gsis && espn && !map.has(gsis)) map.set(gsis, espn);
    }
  }
  return map;
}

// Read espn ids already present in the current headshots.ts so we can preserve
// entries that the crosswalk join can't resolve.
function readExisting() {
  if (!fs.existsSync(OUT)) return {};
  const text = fs.readFileSync(OUT, "utf8");
  const map = {};
  const re = /"([^"]+)":\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(text))) map[m[1]] = m[2];
  return map;
}

async function main() {
  for (const source of SOURCES) await ensureCsv(source);

  const crosswalk = JSON.parse(fs.readFileSync(CROSSWALK, "utf8"));
  const existing = readExisting();
  const gsisToEspn = buildGsisToEspn();

  const result = {};
  let resolved = 0;
  let preserved = 0;
  const missing = [];

  for (const [slug, info] of Object.entries(crosswalk)) {
    const espn = info.gsis ? gsisToEspn.get(info.gsis) : undefined;
    if (espn) {
      result[slug] = headshotUrl(espn);
      resolved++;
    } else if (existing[slug]) {
      result[slug] = existing[slug];
      preserved++;
    } else {
      missing.push(`${slug} (${info.pos}, gsis=${info.gsis})`);
    }
  }

  // Keep any pre-existing entries for slugs no longer in the crosswalk.
  for (const [slug, url] of Object.entries(existing)) {
    if (!(slug in result)) {
      result[slug] = url;
      preserved++;
    }
  }

  const slugs = Object.keys(result).sort();
  const body = slugs
    .map((s) => `  ${JSON.stringify(s)}: ${JSON.stringify(result[s])},`)
    .join("\n");

  const out = `// Player headshot URLs (ESPN), keyed by player slug.
// Generated by scripts/pbp/genHeadshots.mjs from crosswalk.json + nflverse players.csv (espn_id).
// Do not edit by hand; run \`node scripts/pbp/genHeadshots.mjs\` to regenerate.
export const HEADSHOTS: Record<string, string> = {
${body}
};
`;

  fs.writeFileSync(OUT, out);
  console.log(
    `Wrote ${slugs.length} headshots (${resolved} resolved from crosswalk, ${preserved} preserved).`
  );
  if (missing.length) {
    console.log(`No espn_id for ${missing.length} crosswalk slugs:`);
    for (const m of missing) console.log(`  - ${m}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
