// Real-time enrichment pass: stamps each baked play (public/pbp/wN.json) and
// each return (src/data/returns.ts) with `t` — the REAL wall-clock time of the
// play, in seconds since its game's first snap — so real-time power-ups gate on
// real time, not the (delay-prone) game clock. See HANDOFF "Real play time".
//
// Source: lightweight PBP dumps (game_id, qtr, time, time_of_day) saved under
// scripts/pbp/rtdump/*.jsonl (one file per MCP page; harvested from the Stathead
// MCP get_play_by_play tool). We DON'T re-attribute anything — the committed
// w*.json / returns.ts stay the source of truth for scoring; we only add `t`.
//
// Usage: node scripts/pbp/genRealtime.mjs [RTDUMP_DIR]
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const here = new URL('.', import.meta.url);
const RTDUMP = process.argv[2] || join(new URL(here).pathname, 'rtdump');
const pub = (w) => new URL(`../../public/pbp/w${w}.json`, here);
const returnsPath = new URL('../../src/data/returns.ts', here);

const clockOf = (qtr, mmss) => {
  const [m, s] = String(mmss).split(':').map(Number);
  return Math.max(0, Math.min(3599, (qtr - 1) * 900 + (900 - (m * 60 + s))));
};
const teamOf = (slug, crosswalk) =>
  crosswalk[slug]?.team || (/-(k|dst)$/.test(slug) ? slug.replace(/-(k|dst)$/, '').toUpperCase() : null);

// ── Load lightweight dumps → per-game clock→realtime points ──
if (!existsSync(RTDUMP)) { console.error(`RTDUMP not found: ${RTDUMP}`); process.exit(1); }
const rowsByGame = new Map(); // game_id -> [{c, tod}]
let raw = 0;
for (const fn of readdirSync(RTDUMP)) {
  if (!/\.jsonl?$/.test(fn)) continue;
  for (const line of readFileSync(join(RTDUMP, fn), 'utf8').split('\n')) {
    const t = line.trim();
    if (!t.startsWith('{')) continue;
    let d; try { d = JSON.parse(t); } catch { continue; }
    if (!d.game_id || !d.time_of_day || !String(d.game_id).startsWith('2025_')) continue;
    const tod = Date.parse(d.time_of_day);
    if (!Number.isFinite(tod)) continue;
    (rowsByGame.get(d.game_id) || rowsByGame.set(d.game_id, []).get(d.game_id)).push({ c: clockOf(Number(d.qtr), d.time), tod });
    raw++;
  }
}

// Per game: real seconds since the first snap, as a sorted, c-deduped point set.
const clockRt = new Map();  // game_id -> [[c, rt], ...] sorted by c
const teamGame = {};        // week -> team -> game_id
for (const [gid, rows] of rowsByGame) {
  const start = Math.min(...rows.map((r) => r.tod));
  const byC = new Map(); // c -> min rt (earliest real time seen at that clock)
  for (const r of rows) {
    const rt = Math.max(0, Math.round((r.tod - start) / 1000));
    if (!byC.has(r.c) || rt < byC.get(r.c)) byC.set(r.c, rt);
  }
  clockRt.set(gid, [...byC.entries()].map(([c, rt]) => [c, rt]).sort((a, b) => a[0] - b[0]));
  const [, ww, away, home] = gid.split('_');
  const w = +ww;
  (teamGame[w] ||= {})[away] = gid;
  teamGame[w][home] = gid;
}

// Linear interpolation of real time at a game clock along a game's curve.
const rtAt = (pts, c) => {
  if (!pts || !pts.length) return null;
  if (c <= pts[0][0]) return pts[0][0] > 0 ? Math.round((c / pts[0][0]) * pts[0][1]) : 0;
  for (let i = 1; i < pts.length; i++) {
    if (c <= pts[i][0]) {
      const [ca, ra] = pts[i - 1], [cb, rb] = pts[i];
      return cb > ca ? Math.round(ra + ((c - ca) / (cb - ca)) * (rb - ra)) : ra;
    }
  }
  const [cl, rl] = pts[pts.length - 1];
  return rl + (c - cl);
};

const crosswalk = JSON.parse(readFileSync(new URL('crosswalk.json', here), 'utf8'));
const gameFor = (slug, week) => { const tm = teamOf(slug, crosswalk); return tm ? teamGame[week]?.[tm] : undefined; };

// ── Enrich public/pbp/wN.json ──
let hit = 0, miss = 0, noGame = 0;
const weeks = [];
for (let w = 1; w <= 18; w++) {
  const url = pub(w);
  if (!existsSync(url)) continue;
  weeks.push(w);
  const data = JSON.parse(readFileSync(url, 'utf8'));
  for (const [slug, plays] of Object.entries(data.pbp)) {
    const gid = gameFor(slug, w);
    const pts = gid && clockRt.get(gid);
    for (const p of plays) {
      const t = pts ? rtAt(pts, p.c) : null;
      if (t != null) { p.t = t; hit++; } else { delete p.t; (pts ? miss++ : noGame++); }
    }
  }
  writeFileSync(url, JSON.stringify(data));
}

// ── Enrich src/data/returns.ts (tuple → [clock, yards, td, t]) ──
const src = readFileSync(returnsPath, 'utf8');
const m = src.match(/RETURN_PLAYS[^=]*=\s*(\{[\s\S]*?\});/);
let retHit = 0, retMiss = 0;
if (m) {
  const RET = JSON.parse(m[1]);
  for (const [slug, byWeek] of Object.entries(RET)) {
    for (const [wk, tuples] of Object.entries(byWeek)) {
      const gid = gameFor(slug, +wk);
      const pts = gid && clockRt.get(gid);
      byWeek[wk] = tuples.map((tp) => {
        const [c, y, td] = tp;
        const t = pts ? rtAt(pts, c) : null;
        if (t != null) retHit++; else retMiss++;
        return t != null ? [c, y, td ? 1 : 0, t] : [c, y, td ? 1 : 0];
      });
    }
  }
  const out =
`// AUTO-GENERATED by scripts/pbp/genReturns.mjs + genRealtime.mjs — do not edit by hand.
// Real 2025 kick + punt returns per league player, per week (1-14). Shape:
// slug -> { week: [[clock, yards, td(0|1), realTimeSec?], ...] }. \`realTimeSec\` is
// seconds since the game's first snap (for real-time power-up gating); absent
// when the game's real-time map is unavailable. Powers the Return Yards metric.
export type ReturnPlay = [clock: number, yards: number, td: 0 | 1, t?: number];
export const RETURN_PLAYS: Record<string, Record<number, ReturnPlay[]>> = ${JSON.stringify(RET)};

/** Exact-timed return plays for a player slug in a week ([] if none). */
export function returnPlaysFor(slug: string, week: number): ReturnPlay[] {
  return RETURN_PLAYS[slug]?.[week] ?? [];
}
`;
  writeFileSync(returnsPath, out);
}

// ── Report ──
console.log(`rtdump rows: ${raw}  games mapped: ${clockRt.size}`);
console.log(`weeks enriched: ${weeks.join(', ')}`);
console.log(`plays: t set ${hit}, no-rt-at-clock ${miss}, no-game-map ${noGame}`);
console.log(`returns: t set ${retHit}, missed ${retMiss}`);
