// Build src/data/returns.ts from real 2025 KR + PR play-by-play dumps
// (_returns_kr.jsonl / _returns_pr.jsonl, pulled from the StatHead MCP).
// Aggregates kickoff + punt return yards/TDs per league player slug, per week
// (weeks 1-14, matching REAL_WEEKS), via the gsis->slug crosswalk.
//
// Usage: node scripts/pbp/genReturns.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const here = new URL('.', import.meta.url);
const crosswalk = JSON.parse(readFileSync(new URL('crosswalk.json', here), 'utf8'));
const byGsis = new Map();
for (const [slug, info] of Object.entries(crosswalk)) byGsis.set(info.gsis, slug);

const WEEKS = 14;
// slug -> week(1-based index) -> { y, td }
const acc = {};
const add = (file) => {
  const text = readFileSync(new URL(file, here), 'utf8');
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t.startsWith('{')) continue;
    const d = JSON.parse(t);
    if (d.week < 1 || d.week > WEEKS) continue;
    const slug = byGsis.get(d.id);
    if (!slug) continue; // returner not in the league pool — skip
    (acc[slug] ||= {})[d.week] = acc[slug][d.week] || { y: 0, td: 0 };
    acc[slug][d.week].y += d.y;
    acc[slug][d.week].td += d.td;
  }
};
add('_returns_kr.jsonl');
add('_returns_pr.jsonl');

// Emit a compact map: slug -> { week: [yards, tds] } (only weeks with returns,
// only non-trivial yardage kept so the table stays small).
const out = {};
for (const [slug, weeks] of Object.entries(acc)) {
  const w = {};
  for (const [wk, v] of Object.entries(weeks)) {
    if (v.y === 0 && v.td === 0) continue;
    w[wk] = v.td ? [v.y, v.td] : [v.y];
  }
  if (Object.keys(w).length) out[slug] = w;
}

const body =
  '// AUTO-GENERATED by scripts/pbp/genReturns.mjs — do not edit by hand.\n' +
  '// Real 2025 kick + punt return production per league player, per week (1-14).\n' +
  '// Shape: slug -> { week: [returnYards] | [returnYards, returnTds] }.\n' +
  '// Powers the Return Yards metric (unlock-return power-up).\n' +
  'export const RETURN_YARDS: Record<string, Record<number, number[]>> = ' +
  JSON.stringify(out, null, 0) + ';\n\n' +
  '/** Return yards + TDs for a player slug in a week (0/0 if none). */\n' +
  'export function returnsFor(slug: string, week: number): { yds: number; tds: number } {\n' +
  '  const e = RETURN_YARDS[slug]?.[week];\n' +
  '  return e ? { yds: e[0] ?? 0, tds: e[1] ?? 0 } : { yds: 0, tds: 0 };\n' +
  '}\n';

writeFileSync(new URL('../../src/data/returns.ts', here), body);
const players = Object.keys(out).length;
console.log(`returns.ts written: ${players} returners with data`);
