// Build src/data/returns.ts from real 2025 KR + PR play-by-play dumps with
// EXACT game clocks (_ret_kr.jsonl / _ret_pr.jsonl, pulled from the StatHead
// MCP with qtr+time). Each return becomes one play at its real game-elapsed
// second — no synthesized timing. Keyed by league player slug, weeks 1-14.
//
// Usage: node scripts/pbp/genReturns.mjs
// NOTE: this emits returns with game clocks only. Re-run scripts/pbp/genRealtime.mjs
// AFTER this to re-stamp each return with its real wall-clock time `t` (for
// real-time power-up gating) — otherwise returns.ts loses the `t` column.
import { readFileSync, writeFileSync } from 'node:fs';

const here = new URL('.', import.meta.url);
const crosswalk = JSON.parse(readFileSync(new URL('crosswalk.json', here), 'utf8'));
const byGsis = new Map();
for (const [slug, info] of Object.entries(crosswalk)) byGsis.set(info.gsis, slug);

const WEEKS = 14;
// Same clock convention as genRealPbp.mjs: game-elapsed seconds from qtr + the
// MM:SS remaining in that quarter, capped at 3599.
function clockOf(qtr, mmss) {
  const [m, s] = String(mmss).split(':').map(Number);
  return Math.max(0, Math.min(3599, (qtr - 1) * 900 + (900 - (m * 60 + s))));
}

// slug -> week -> [ [clock, yards, td], ... ]
const acc = {};
const add = (file) => {
  const text = readFileSync(new URL(file, here), 'utf8');
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t.startsWith('{')) continue;
    const d = JSON.parse(t);
    if (d.week < 1 || d.week > WEEKS) continue;
    const slug = byGsis.get(d.id);
    if (!slug) continue; // returner not in the league pool — skip
    const c = clockOf(d.qtr, d.time);
    ((acc[slug] ||= {})[d.week] ||= []).push([c, d.y, d.td]);
  }
};
add('_ret_kr.jsonl');
add('_ret_pr.jsonl');

// Sort each week's returns by clock; drop weeks with no net production so the
// table stays lean (a player with only 0-yard fair catches isn't selectable
// value, but keep them if they have any non-zero yard or TD).
const out = {};
for (const [slug, weeks] of Object.entries(acc)) {
  const w = {};
  for (const [wk, plays] of Object.entries(weeks)) {
    plays.sort((a, b) => a[0] - b[0]);
    const hasValue = plays.some((p) => p[1] !== 0 || p[2] !== 0);
    if (!hasValue) continue;
    // emit [clock, yards] or [clock, yards, 1] for return TDs
    w[wk] = plays.map((p) => (p[2] ? [p[0], p[1], 1] : [p[0], p[1]]));
  }
  if (Object.keys(w).length) out[slug] = w;
}

const body =
  '// AUTO-GENERATED by scripts/pbp/genReturns.mjs — do not edit by hand.\n' +
  '// Real 2025 kick + punt returns per league player, per week (1-14), each at\n' +
  '// its EXACT game-elapsed second. Shape: slug -> { week: [[clock, yards] |\n' +
  '// [clock, yards, 1(returnTD)], ...] }. Powers the Return Yards metric.\n' +
  'export type ReturnPlay = [clock: number, yards: number, td?: 1];\n' +
  'export const RETURN_PLAYS: Record<string, Record<number, ReturnPlay[]>> = ' +
  JSON.stringify(out) + ';\n\n' +
  '/** Exact-timed return plays for a player slug in a week ([] if none). */\n' +
  'export function returnPlaysFor(slug: string, week: number): ReturnPlay[] {\n' +
  '  return RETURN_PLAYS[slug]?.[week] ?? [];\n' +
  '}\n';

writeFileSync(new URL('../../src/data/returns.ts', here), body);
console.log(`returns.ts written: ${Object.keys(out).length} returners with exact-timed plays`);
