// Publish the drift between the BAKED player→team map and Sleeper's live
// directory into player_team_override (0142).
//
// The client's team knowledge is baked (playerBio.ts, regenerated by
// scripts/gen-player-bio.mjs). Rosters churn daily — trades, cuts, signings,
// cut-down day hardest of all — and the app can't wait for a redeploy to know
// a player moved. The worker already refreshes its directory copy daily; this
// runs right after, storing ONLY the players whose current team differs from
// the bake (a NULL team is a real answer: cut/free agent). Rows matching the
// bake again (a re-bake shipped, or a player returned) are deleted, so the
// table stays the size of the drift — dozens to a few hundred rows.
//
// Same fantasy-position filter as the bake: a slug the bake doesn't know is
// skipped rather than published, because clients overlay this ON TOP of the
// bake — an override for an unbaked slug would answer teamFor() for players
// no surface renders, growing the table for nothing.
import { PLAYER_BIO } from '../../../packages/core/src/data/playerBio.ts';
import { db } from '../supabase.js';

/** Diff the (already-built) player index against the bake and reconcile the
 *  override table. Returns { changed, cleared } for the log line. */
export async function syncTeamOverrides(playerIndex) {
  const live = new Map();
  for (const { slug, team } of playerIndex.allSlugs()) live.set(slug, team ?? null);
  return reconcileTeamOverrides(live);
}

/** Publish a slug → team map as the drift against the bake (v0.305.0).
 *
 *  Split out of `syncTeamOverrides` so the two sources that know where a player
 *  plays can share one writer. Sleeper's directory is the daily one — 14MB, and
 *  Sleeper asks for at most one pull a day — while the ESPN roster sweep beside
 *  it runs several times a day, which is what a cut-down week actually needs.
 *  They agree about the table because they agree about this function: only the
 *  MAP differs, never what is done with it.
 *
 *  `full` says whether the caller saw the WHOLE league. A partial map (one team
 *  fetch failed) may only ADD what it saw — it cannot conclude that a player it
 *  never looked for has no team, and a sweep that silently released half the
 *  league on one bad afternoon is the failure worth designing against. */
export async function reconcileTeamOverrides(liveTeams, full = true) {
  const want = new Map(); // slug -> team|null, only where it differs from the bake
  for (const [slug, team] of liveTeams) {
    const baked = PLAYER_BIO[slug];
    if (!baked) continue;                    // unbaked slug: nothing overlays it
    const live = team ?? null;
    const base = baked.team ?? null;
    if (live !== base) want.set(slug, live);
  }

  const { data: existing, error: exErr } = await db().from('player_team_override').select('slug,team');
  if (exErr) throw new Error(`override scan: ${exErr.message}`);
  const have = new Map((existing ?? []).map((r) => [r.slug, r.team ?? null]));

  const upserts = [];
  for (const [slug, team] of want) {
    if (!have.has(slug) || have.get(slug) !== team) upserts.push({ slug, team, updated_at: new Date().toISOString() });
  }
  // A partial sweep never prunes: absence from a map that didn't look at every
  // team is not evidence that the drift ended.
  const stale = full ? [...have.keys()].filter((slug) => !want.has(slug)) : [];

  if (upserts.length) {
    const { error } = await db().from('player_team_override').upsert(upserts, { onConflict: 'slug' });
    if (error) throw new Error(`override upsert (${upserts.length}): ${error.message}`);
  }
  if (stale.length) {
    const { error } = await db().from('player_team_override').delete().in('slug', stale);
    if (error) throw new Error(`override prune (${stale.length}): ${error.message}`);
  }
  return { changed: upserts.length, cleared: stale.length, standing: want.size };
}
