// @computer (v0.537.0): which chat lines become issues, and what they say.
import { isComputerAsk, issueTitle, issueBody, SNARK, snarkFor, contextSection, fixReport, fixSummary, titleSummary, closedHeader } from '../src/computer.js';

let fails = 0;
const ok = (name, cond, got) => {
  if (!cond) { fails++; console.log(`FAIL ${name}${got !== undefined ? ` — got ${JSON.stringify(got)}` : ''}`); }
  else console.log(`ok   ${name}`);
};

ok('a leading tag asks', isComputerAsk('@computer why did I lose?'));
ok('a tag mid-line asks', isComputerAsk('hey @Computer, check the LB scores'));
ok('a longer handle does not', !isComputerAsk('@computers are great'));
ok('no tag, no ask', !isComputerAsk('computer, why?'));
ok('nothing, no ask', !isComputerAsk(null));
ok('the title drops the tag', issueTitle('@computer why 8-2?') === '@computer: why 8-2?', issueTitle('@computer why 8-2?'));
ok('…and stays one short line', issueTitle('@computer ' + 'x'.repeat(200)).length <= 90);
ok('an image-only ask still gets a title', issueTitle('') === '@computer: (image)');
const b = issueBody({ body: 'why is this broken @computer', where: 'Kickoff League (abc)', at: 't' });
ok('the body keeps the trigger phrase', b.includes('@computer'));
ok('…names where it was asked', b.includes('Kickoff League (abc)'));
const img = issueBody({ body: 'look', image: 'https://x/y.png', where: 'L', at: 't' });
ok('an untagged line gets the phrase so the Action fires', img.split('\n')[2].startsWith('@computer '));
ok('…and the picture is embedded', img.includes('![attached](https://x/y.png)'));

ok('twenty lines in the bank', SNARK.length === 20, SNARK.length);
ok('no two alike', new Set(SNARK).size === SNARK.length);
ok('the same line always gets the same reply', snarkFor(12345) === snarkFor(12345));
ok('neighbouring lines get different ones', snarkFor(1) !== snarkFor(2));
ok('every reply fits a chat line', SNARK.every((l) => l.length + 8 <= 500));

// v0.598.0 — the closed-issue card: a header in the chat, a report to expand.
const note = '✅ Fixed in #1048 (v0.561.9). Kickoff League\'s waiver schedule is daily now. It runs at 4 AM ET.\n\n- **Every day:** waivers run at **4:00 AM ET**.\n- See [the PR](https://github.com/x/y/pull/1).\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const sum = fixSummary(note);
ok('the summary is the first two sentences, opener dropped', sum === "Kickoff League's waiver schedule is daily now. It runs at 4 AM ET.", sum);
ok('…and stays short', fixSummary('x'.repeat(900)).length <= 220);
const rep = fixReport(note);
ok('the report keeps its lines as bullets', rep.includes('\n• Every day: waivers run at 4:00 AM ET.'), rep);
ok('…drops the footer, markdown and links', !rep.includes('Generated by') && !rep.includes('**') && !rep.includes(']('), rep);
const prBody = '**Cause**\n\nThe slate says LA.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_x';
ok('…and a PR body\'s attribution lines', fixReport(prBody) === 'Cause\n\nThe slate says LA.', fixReport(prBody));
ok('…never re-tags', !/@computer/i.test(fixReport('ask @computer again')));
ok('…fits', fixReport('y'.repeat(5000)).length <= 1500);
ok('a PR title becomes a sentence', titleSummary("v0.597.0: Rams players no longer lock at Thursday's kickoff (#1095)") === "Rams players no longer lock at Thursday's kickoff.", titleSummary("v0.597.0: Rams players no longer lock at Thursday's kickoff (#1095)"));
ok('the header', closedHeader(1095, "Rams players no longer lock at Thursday's kickoff.") === "Issue #1095 closed. Rams players no longer lock at Thursday's kickoff.");
ok('…punctuates', closedHeader(7, 'Done') === 'Issue #7 closed. Done.');
ok('…says not planned', closedHeader(8, '', true) === 'Issue #8 closed (not planned).');

// v0.595.0: the chat before the ask, names hidden
{
  const me = 'u-me';
  const ctx = contextSection([
    { author_id: 'u-dave', body: 'my QB got 9 pts @Dave Jr and @computer', created_at: '2026-10-03T02:30:00Z' },
    { author_id: me, body: 'https://cdn.example/shot.png', caption: 'look @Dave', created_at: '2026-10-03T02:33:00Z' },
    { author_id: 'u-amy', body: 'https://cdn.example/hers.png', created_at: '2026-10-03T02:34:00Z' },
    { author_id: 'u-dave', body: 'same', created_at: '2026-10-03T02:35:00Z' },
    { author_id: null, kind: 'computer', body: 'Beep boop.', created_at: '2026-10-03T02:35:30Z' },
  ], me);
  ok('others become Member A, B in order', ctx.includes('**Member A** · 2026-10-03 02:30') && ctx.includes('**Member B** · 2026-10-03 02:34') && ctx.split('**Member A**').length === 3, ctx);
  ok('no member id or handle leaks', !ctx.includes('u-dave') && !ctx.includes('u-amy') && !/@Dave\b(?! )/.test(ctx.split('**Asker**')[0]), ctx);
  ok('others\' @mentions are masked, @computer kept', ctx.includes('@member Jr and @computer'), ctx);
  ok('the asker\'s screenshot goes in', ctx.includes('**Asker** · 2026-10-03 02:33 — ![image](https://cdn.example/shot.png) look @Dave'), ctx);
  ok('others\' pictures stay out', !ctx.includes('hers.png') && ctx.includes('**Member B** · 2026-10-03 02:34 — (image)'), ctx);
  ok('house lines are the Computer', ctx.includes('**Computer** · 2026-10-03 02:35 — Beep boop.'));
  ok('no chat, no section', contextSection([], me) === '');
  const body = issueBody({ body: '@computer I thought we fixed this.', where: 'L', at: 't', context: ctx });
  ok('the header counts messages, not minutes', ctx.startsWith('**Chat before the ask** (last 3 messages'), ctx);
  ok('the issue carries it, before the marker', body.indexOf('Chat before the ask') > body.indexOf('I thought') && body.trim().endsWith('<!-- ffgame-computer -->'));
}

if (fails) { console.log(`\n${fails} @COMPUTER ASSERTION(S) FAILED`); process.exit(1); }
console.log('\nALL @COMPUTER ASSERTIONS PASSED');
