// @computer (v0.537.0): which chat lines become issues, and what they say.
import { isComputerAsk, issueTitle, issueBody, SNARK, snarkFor, fixLine, contextSection } from '../src/computer.js';

let fails = 0;
const ok = (name, cond, got) => {
  if (!cond) { fails++; console.log(`FAIL ${name}${got !== undefined ? ` — got ${JSON.stringify(got)}` : ''}`); }
  else console.log(`ok   ${name}`);
};

ok('a leading tag asks', isComputerAsk('@computer why did I lose?'));
ok('a tag mid-line asks', isComputerAsk('hey @Computer, check the LB scores'));
ok('a longer handle does not', !isComputerAsk('@computers are great'));
ok('no tag, no ask', !isComputerAsk('computer, why?'));
ok('nothing, no ask', !isComputerAsk(null));
ok('the title drops the tag', issueTitle('@computer why 8-2?') === '@computer: why 8-2?', issueTitle('@computer why 8-2?'));
ok('…and stays one short line', issueTitle('@computer ' + 'x'.repeat(200)).length <= 90);
ok('an image-only ask still gets a title', issueTitle('') === '@computer: (image)');
const b = issueBody({ body: 'why is this broken @computer', where: 'Kickoff League (abc)', at: 't' });
ok('the body keeps the trigger phrase', b.includes('@computer'));
ok('…names where it was asked', b.includes('Kickoff League (abc)'));
const img = issueBody({ body: 'look', image: 'https://x/y.png', where: 'L', at: 't' });
ok('an untagged line gets the phrase so the Action fires', img.split('\n')[2].startsWith('@computer '));
ok('…and the picture is embedded', img.includes('![attached](https://x/y.png)'));

ok('twenty lines in the bank', SNARK.length === 20, SNARK.length);
ok('no two alike', new Set(SNARK).size === SNARK.length);
ok('the same line always gets the same reply', snarkFor(12345) === snarkFor(12345));
ok('neighbouring lines get different ones', snarkFor(1) !== snarkFor(2));
ok('every reply fits a chat line', SNARK.every((l) => l.length + 8 <= 500));

// v0.562.0 — the fix note, back in the chat.
const note = '✅ Fixed in #1048 (v0.561.9). Kickoff League\'s waiver schedule:\n\n- **Every day:** waivers run at **4:00 AM ET**.\n- See [the PR](https://github.com/x/y/pull/1).\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const fl = fixLine(1047, note);
ok('a fix line leads with the issue', fl.startsWith('✅ Fixed (#1047): '), fl);
ok('…drops the footer', !fl.includes('Generated by'), fl);
ok('…drops markdown and keeps link words', !fl.includes('**') && !fl.includes('](') && fl.includes('the PR'), fl);
ok('…is one line', !fl.includes('\n'), fl);
ok('…never re-tags', !/@computer/i.test(fixLine(1, 'ask @computer again')));
ok('…fits a chat line', fixLine(1, 'x'.repeat(2000)).length <= 480);
ok('no note still says fixed', fixLine(9, null) === '✅ Fixed (#9).');
ok('…and the note\'s own "✅ Fixed in #…" opener is not repeated', fixLine(1047, note).startsWith('✅ Fixed (#1047): Kickoff'), fixLine(1047, note));

// v0.595.0: the chat before the ask, names hidden
{
  const me = 'u-me';
  const ctx = contextSection([
    { author_id: 'u-dave', body: 'my QB got 9 pts @Dave Jr and @computer', created_at: '2026-10-03T02:30:00Z' },
    { author_id: me, body: 'https://cdn.example/shot.png', caption: 'look @Dave', created_at: '2026-10-03T02:33:00Z' },
    { author_id: 'u-amy', body: 'https://cdn.example/hers.png', created_at: '2026-10-03T02:34:00Z' },
    { author_id: 'u-dave', body: 'same', created_at: '2026-10-03T02:35:00Z' },
    { author_id: null, kind: 'computer', body: 'Beep boop.', created_at: '2026-10-03T02:35:30Z' },
  ], me);
  ok('others become Member A, B in order', ctx.includes('**Member A** · 02:30') && ctx.includes('**Member B** · 02:34') && ctx.split('**Member A**').length === 3, ctx);
  ok('no member id or handle leaks', !ctx.includes('u-dave') && !ctx.includes('u-amy') && !/@Dave\b(?! )/.test(ctx.split('**Asker**')[0]), ctx);
  ok('others\' @mentions are masked, @computer kept', ctx.includes('@member Jr and @computer'), ctx);
  ok('the asker\'s screenshot goes in', ctx.includes('**Asker** · 02:33 — ![image](https://cdn.example/shot.png) look @Dave'), ctx);
  ok('others\' pictures stay out', !ctx.includes('hers.png') && ctx.includes('**Member B** · 02:34 — (image)'), ctx);
  ok('house lines are the Computer', ctx.includes('**Computer** · 02:35 — Beep boop.'));
  ok('no chat, no section', contextSection([], me) === '');
  const body = issueBody({ body: '@computer I thought we fixed this.', where: 'L', at: 't', context: ctx });
  ok('the issue carries it, before the marker', body.indexOf('Chat before the ask') > body.indexOf('I thought') && body.trim().endsWith('<!-- ffgame-computer -->'));
}

if (fails) { console.log(`\n${fails} @COMPUTER ASSERTION(S) FAILED`); process.exit(1); }
console.log('\nALL @COMPUTER ASSERTIONS PASSED');
