// The player card (to-do list: "Player stats cards when you click an NFL
// player anywhere") — one modal, opened from any surface via a module-level
// bus so wiring a new surface is a one-line `openPlayerCard({...})` with no
// context threading. <PlayerCardHost/> mounts once in App and renders it.
//
// Content is assembled from what core already knows, no new fetches on open
// except the ★ set: identity (headshot/crest), the baked bio (tenure, college,
// jersey, age — playerBio.ts, regenerated by scripts/gen-player-bio.mjs), the
// LIVE injury detail (designation + return date + comment, the 0133 feed via
// injuryRowFor), this week's statline when plays are loaded, and the baked
// 2025 season line. A slug some source doesn't know simply omits that row.
import { useEffect, useState } from 'react';
import type { Pos } from '@drip/core/types';
import { PLAYER_BIO, tenureLabel } from '@drip/core/data/playerBio';
import { injuryFor, injuryRowFor } from '@drip/core/data/injuries';
import { flagFor } from '@drip/core/data/commish';
import { displayTeam } from '@drip/core/data/playerTeam';
import { statsForName } from '@drip/core/data/players';
import { statlineAt, fmtStat } from '@drip/core/engine/sim';
import { teamLogo } from '@drip/core/data/media';
import { myFavorites, setFavorite, nativeRosters, matchupTeams, leagueRegister, type RegisterRow } from '@drip/core/data/liveApi';
import { nflGameForTeam, kickoffLabel } from '@drip/core/data/nflSlate';
import { PROJ_2026 } from '@drip/core/data/proj2026';
import { ModalBackdrop, PlayerImg, Img, InjuryBadge } from './ui';
import { Ev, track } from '@drip/core/analytics';

export interface PlayerCardReq {
  slug: string; name: string; pos: string; team: string;
  /** Board week for the live statline + injury report; omit on week-less surfaces. */
  week?: number;
  /** Signed-in account — lights the ★ (omitted → star hidden, e.g. demo). */
  userId?: string;
  /** The league the card was opened FROM, when there is one — it buys the two
   *  panels a bare NFL card cannot have: who owns him here, and what this
   *  league has done with him (0186's register). */
  leagueId?: string;
}

let listener: ((p: PlayerCardReq) => void) | null = null;

/** WHICH LEAGUE IS ON SCREEN (v0.282.0). Installed by the surface that knows —
 *  the same bus reasoning as the card itself: threading a `leagueId` prop
 *  through every roster row, picker and board cell to reach a module-level
 *  modal would be prop-drilling for one consumer. Cleared when the league
 *  closes, so a card opened elsewhere never claims the last league's owner. */
let cardLeague: string | null = null;
export const setCardLeague = (id: string | null): void => { cardLeague = id; };

export const openPlayerCard = (p: PlayerCardReq): void => {
  track(Ev.playerCardOpened, { pos: p.pos });
  listener?.({ ...p, leagueId: p.leagueId ?? cardLeague ?? undefined });
};

const INJURY_LABEL: Record<string, string> = { O: 'Out', IR: 'Injured Reserve', D: 'Doubtful', Q: 'Questionable' };

export function PlayerCardHost() {
  const [req, setReq] = useState<PlayerCardReq | null>(null);
  useEffect(() => { listener = setReq; return () => { listener = null; }; }, []);
  if (!req) return null;
  return <PlayerCardModal req={req} onClose={() => setReq(null)} />;
}

function PlayerCardModal({ req, onClose }: { req: PlayerCardReq; onClose: () => void }) {
  const { slug, name, pos, team, week, userId, leagueId } = req;
  // SUMMARY | HISTORY. No GAME LOG or TEAM tab, deliberately: a per-week NFL
  // stat table and a depth chart are data this app does not hold, and an empty
  // tab is worse than no tab.
  const [tab, setTab] = useState<'summary' | 'history'>('summary');
  const [owner, setOwner] = useState<string | null | undefined>(undefined); // undefined = unknown, null = free agent
  const [moves, setMoves] = useState<RegisterRow[] | null>(null);
  useEffect(() => {
    if (!leagueId) { setOwner(undefined); setMoves(null); return; }
    let dead = false;
    nativeRosters(leagueId)
      .then(async (rows) => {
        const mine = rows.find((r) => r.slug === slug);
        if (dead) return;
        if (!mine) { setOwner(null); return; }
        const teams = await matchupTeams(leagueId, [mine.roster_id]).catch(() => ({} as Record<number, { team_name: string }>));
        if (!dead) setOwner(teams[mine.roster_id]?.team_name ?? `Roster ${mine.roster_id}`);
      })
      .catch(() => { if (!dead) setOwner(undefined); });
    leagueRegister(leagueId, 200)
      .then((r) => { if (!dead && r.ok) setMoves((r.rows ?? []).filter((x) => x.slug === slug)); })
      .catch(() => {});
    return () => { dead = true; };
  }, [leagueId, slug]);
  // The card is where a stale team is most visible — prefer the live layer
  // (fresh directory bake + worker overrides, 0142) over whatever the opening
  // surface happened to know.
  const showTeam = displayTeam(slug, team);
  const bio = PLAYER_BIO[slug];
  const tenure = tenureLabel(slug);
  const inj = week != null ? injuryRowFor(week, slug) : null;
  const flag = flagFor(slug);
  const injTag = week != null ? injuryFor(week, slug) : null;
  const season = statsForName(name, pos as Pos);
  // This week so far, from whatever plays are loaded (live board installs them;
  // elsewhere this is legitimately all zeroes and we hide the row).
  const weekLine = (() => {
    if (week == null) return null;
    try {
      const p = { id: slug, name, full: name, pos: pos as Pos, team, stats: season };
      const s = statlineAt(p, week, Number.MAX_SAFE_INTEGER);
      const any = s.passYds || s.rushYds || s.recYds || s.carries || s.rec || s.targets || s.fg || s.xp || s.sacks || s.tackles;
      return any ? fmtStat(pos as Pos, s, true) : null;
    } catch { return null; }
  })();
  const seasonLine = season.games > 0
    ? `${season.games} G · ${Math.round(season.ppr)} PPR` + (
      pos === 'QB' ? ` · ${season.passYds} pass yd · ${season.passTds} TD`
      : pos === 'RB' ? ` · ${season.rushYds} ru yd · ${season.rushTds + season.recTds} TD`
      : pos === 'WR' || pos === 'TE' ? ` · ${season.receptions}/${season.targets}-${season.recYds} rec · ${season.recTds} TD`
      : '')
    : null;

  const [starred, setStarred] = useState<boolean | null>(null); // null = loading/hidden
  useEffect(() => {
    let alive = true;
    if (!userId) { setStarred(null); return; }
    myFavorites().then((f) => { if (alive) setStarred(f.has(slug)); });
    return () => { alive = false; };
  }, [slug, userId]);
  const toggleStar = () => {
    if (!userId || starred == null) return;
    const next = !starred;
    setStarred(next); // optimistic; a failure just re-reads next open
    setFavorite(userId, slug, next).catch(() => setStarred(!next));
  };

  const row = (label: string, value: string) => (
    <div style={{ display: 'flex', gap: 10, alignItems: 'baseline' }}>
      <span className="mono" style={{ flex: 'none', width: 64, fontSize: 8.5, fontWeight: 700, letterSpacing: '0.1em', color: 'var(--faint)' }}>{label}</span>
      <span className="mono" style={{ fontSize: 11, color: 'var(--text)', minWidth: 0 }}>{value}</span>
    </div>
  );

  return (
    <ModalBackdrop onClick={onClose} zIndex={90}>
      <div onClick={(e) => e.stopPropagation()} style={{ width: 'min(420px, 92vw)', background: 'var(--surface)', border: '1px solid var(--bd)', borderRadius: 8, padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <PlayerImg playerId={slug} team={team} pos={pos as Pos} size={56} />
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span className="grotesk" style={{ fontSize: 18, fontWeight: 700, color: 'var(--text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{name}</span>
              {week != null && <InjuryBadge week={week} slug={slug} />}
            </div>
            <div className="mono" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 10, color: 'var(--dim)', marginTop: 3 }}>
              <span style={{ fontWeight: 700 }}>{pos}</span>
              <Img src={teamLogo(showTeam)} size={13} radius={2} fallback={<span />} />
              <span>{showTeam || 'FA'}</span>
              {bio?.num != null && <span>· #{bio.num}</span>}
            </div>
          </div>
          {userId && starred != null && (
            <button onClick={toggleStar} title={starred ? 'Unstar' : 'Star for personal reference'} style={{ background: 'none', border: 'none', fontSize: 22, cursor: 'pointer', color: starred ? '#E8B23A' : 'var(--faint)', lineHeight: 1 }}>{starred ? '★' : '☆'}</button>
          )}
        </div>
        {/* THE FACT STRIP (v0.282.0) — the numbers a card is opened for, read
            at a glance. Height and weight are NOT here: the bake carries age,
            tenure, college and jersey, and inventing two more would be worse
            than four honest columns. */}
        <div style={{ display: 'flex', borderTop: '1px solid var(--bd)', borderBottom: '1px solid var(--bd)', padding: '9px 0' }}>
          {([
            ['AGE', bio?.age != null ? String(bio.age) : '—'],
            ['EXP', bio?.exp != null ? (bio.exp === 0 ? 'ROOK' : `${bio.exp} yr`) : '—'],
            ['NO.', bio?.num != null ? `#${bio.num}` : '—'],
            ['PROJ', PROJ_2026.get(slug) != null ? (PROJ_2026.get(slug) as number).toFixed(1) : '—'],
          ] as const).map(([k, v]) => (
            <div key={k} style={{ flex: 1, textAlign: 'center' }}>
              <div className="mono" style={{ fontSize: 8, fontWeight: 700, letterSpacing: '0.12em', color: 'var(--faint)' }}>{k}</div>
              <div className="grotesk" style={{ fontSize: 15, fontWeight: 800, color: 'var(--text)', marginTop: 2 }}>{v}</div>
            </div>
          ))}
        </div>

        {!!leagueId && (
          <div style={{ display: 'flex', gap: 6 }}>
            {([['summary', 'SUMMARY'], ['history', `HISTORY${moves?.length ? ` (${moves.length})` : ''}`]] as const).map(([id, label]) => (
              <button key={id} onClick={() => setTab(id)} className="mono"
                style={{ fontSize: 9.5, fontWeight: 700, cursor: 'pointer', borderRadius: 5, padding: '5px 10px',
                  color: tab === id ? 'var(--you)' : 'var(--dim)', background: tab === id ? 'var(--bg)' : 'transparent',
                  border: `1px solid ${tab === id ? 'var(--you)' : 'var(--bd)'}` }}>{label}</button>
            ))}
          </div>
        )}

        {(!leagueId || tab === 'summary') && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {(() => {
              if (week == null || !showTeam) return null;
              const g = nflGameForTeam(week, showTeam);
              if (!g) return row('NEXT UP', 'bye — no game this week');
              const home = g.home === showTeam;
              const when = g.kickoff ? kickoffLabel(g.kickoff) : '';
              return row('NEXT UP', `${home ? 'vs' : '@'} ${home ? g.away : g.home}${when ? ` · ${when}` : ''}`);
            })()}
            {owner !== undefined && row('ROSTERED', owner ? `⇄ ${owner}` : 'free agent — nobody holds him')}
            {(tenure || bio?.college) && row('CAREER', [tenure, bio?.college].filter(Boolean).join(' · '))}
            {inj && row('INJURY', `${INJURY_LABEL[inj.status] ?? inj.status}${inj.comment ? ` — ${inj.comment}` : ''}${inj.returnDate ? ` · est. return ${inj.returnDate}` : ''}`)}
            {!inj && injTag && row('INJURY', INJURY_LABEL[injTag] ?? injTag)}
            {flag && row('COMMISH', `\u2691 ${flag}`)}
            {weekLine && row('THIS WK', weekLine)}
            {seasonLine && row('2025', seasonLine)}
          </div>
        )}

        {/* HISTORY — this LEAGUE's transaction record for him (0186). Sleeper's
            is the whole platform's; ours is the league's, which is the half a
            manager actually argues about. */}
        {!!leagueId && tab === 'history' && (
          <div style={{ display: 'flex', flexDirection: 'column', maxHeight: 300, overflowY: 'auto' }}>
            {moves === null && <span className="mono" style={{ fontSize: 10, color: 'var(--faint)' }}>Loading…</span>}
            {moves?.length === 0 && (
              <span className="mono" style={{ fontSize: 10, color: 'var(--faint)', lineHeight: 1.6 }}>
                No moves yet. Adds, drops, claims and trades appear here from the moment the draft ends —
                draft night itself is in the draft room.
              </span>
            )}
            {moves?.map((m) => (
              <div key={m.id} style={{ display: 'flex', gap: 9, padding: '6px 0', borderBottom: '1px solid var(--bd)' }}>
                <span style={{ width: 16, textAlign: 'center', color: m.kind === 'drop' ? 'var(--opp)' : 'var(--you)' }}>
                  {m.kind === 'drop' ? '✕' : m.kind === 'trade' ? '⇄' : m.kind === 'waiver' ? '⚑' : '✚'}
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 12, lineHeight: 1.5, color: 'var(--text)' }}>
                    <b>{m.team ?? `Roster ${m.roster_id}`}</b>
                    {m.kind === 'drop' ? ' dropped him'
                      : m.kind === 'trade' ? ` traded for him${m.from_team ? ` from ${m.from_team}` : ''}`
                      : m.kind === 'waiver' ? ` claimed him off waivers${m.bid ? ` for ${m.bid}` : ''}`
                      : m.kind === 'commish' ? ' — moved by the commissioner'
                      : ' signed him'}
                  </div>
                  <div className="mono" style={{ fontSize: 8.5, color: 'var(--faint)', marginTop: 1 }}>
                    {(() => { const d = new Date(m.at); return Number.isNaN(d.getTime()) ? '' : d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); })()}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </ModalBackdrop>
  );
}
