// THE TIME ZONES THE APP SHIPS (v0.502.0) — a trimmed copy of formatjs's
// `add-golden-tz`, written to apps/mobile/src/intl-tz-data.js.
//
// WHY: the Hermes Intl polyfill (apps/mobile/src/intl-polyfill.ts) needed
// zone data, and `add-golden-tz` was 794 KB of the JS bundle — which ships
// UNCOMPRESSED in the APK, so every byte of it was a byte of download. Almost
// all of that is history: each zone's offset changes from the 1880s to 2099.
// The app formats kickoffs, locks and "now", so it needs the rules in force
// from 2020 on, not Victorian railway time.
//
// WHAT IS KEPT: EVERY zone. The polyfill takes the phone's own zone as its
// default (expo-localization), and a zone missing from the data formats as
// UTC — the "locks 8:25 PM" bug that file's header describes. So nothing is
// dropped but history: each zone starts with the rule in force at FROM, keeps
// its transitions up to UNTIL, and ends with the rule in force after the last
// one it kept (formatjs's terminal entry). A date before FROM formats with
// FROM's rule — right for every US zone since 2007, and nothing here shows a
// date that old.
//
// RUN after a formatjs upgrade:  node scripts/gen-tz-data.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const FROM = Date.UTC(2020, 0, 1) / 1000;
const UNTIL = Date.UTC(2041, 0, 1) / 1000;

const require = createRequire(import.meta.url);
const srcPath = require.resolve('@formatjs/intl-datetimeformat/add-golden-tz.js', { paths: [new URL('../apps/mobile/', import.meta.url).pathname] });
const src = readFileSync(srcPath, 'utf8');
let data;
// The file is one guarded call; hand it a stand-in Intl and keep the payload.
new Function('Intl', src.replace(/^[\s\S]*?if \(/, 'if ('))({ DateTimeFormat: { __addTZData: (d) => { data = d; } } });
if (!data?.zones?.length) throw new Error('no zone data parsed from ' + srcPath);

// formatjs's own reading of a timestamp: base 36 seconds, '' = -Infinity. The
// terminal entry is written 'NaN' — which parseInt reads as a small positive
// number, so the lookup walks past it and uses it as the after-everything rule.
const ts = (t) => (t === '' ? -Infinity : t === 'NaN' ? Infinity : parseInt(t, 36));
const zones = data.zones.map((z) => {
  const [name, ...entries] = z.split('|');
  const rows = entries.map((e) => { const [t, ...rest] = e.split(','); return { t, at: ts(t), rest: rest.join(',') }; });
  let start = rows[0];
  const kept = [];
  for (const r of rows) {
    if (r.at <= FROM) start = r;
    else if (r.at < UNTIL && r.t !== 'NaN') kept.push(r);
  }
  const last = kept.length ? kept[kept.length - 1] : start;
  return [name, `,${start.rest}`, ...kept.map((r) => `${r.t},${r.rest}`), `NaN,${last.rest}`].join('|');
});

const out = `// @generated by scripts/gen-tz-data.mjs from @formatjs/intl-datetimeformat/add-golden-tz.js
// — every zone, history trimmed to ${new Date(FROM * 1000).getUTCFullYear()}–${new Date(UNTIL * 1000).getUTCFullYear() - 1}. Do not edit; re-run the script.
// prettier-ignore
if ('DateTimeFormat' in Intl && Intl.DateTimeFormat.__addTZData) {
  Intl.DateTimeFormat.__addTZData(${JSON.stringify({ abbrvs: data.abbrvs, offsets: data.offsets, zones })});
}
`;
const dest = new URL('../apps/mobile/src/intl-tz-data.js', import.meta.url);
writeFileSync(dest, out);
console.log(`${zones.length} zones · ${(src.length / 1024).toFixed(0)} KB → ${(out.length / 1024).toFixed(0)} KB · ${dest.pathname}`);
