-- 0099: re-stamp the 2026 preseason slate (0056) with DERIVED window ids.
-- 0056 bucketed every non-Sun/Mon game as 'tnf' (the server's old fixed-five
-- windowFromKickoff), but the client derives window ids from real kickoffs
-- (nflSlate.ts windowIdsFromKickoffs): Friday games are 'fri', Saturday slates
-- split into 'sat'/'sat2'/…, a late Thursday doubleheader is 'tnf2'. The `win`
-- column keys per-window pick sealing (worker lock.js) and the 0058 lock
-- trigger, so the mismatch left those windows never sealing. The worker now
-- writes these same derived ids live (slateFromGames); this migration corrects
-- the preloaded rows so the board and trigger are right before its first
-- preseason tick. Values generated by the shared derivation itself. Idempotent.
delete from nfl_slate where season = '2026' and week in (101, 102, 103);
insert into nfl_slate (season, week, home, away, win, kickoff) values
  ('2026', 101, 'ARI', 'CAR', 'tnf', '2026-08-07T00:00Z'),
  ('2026', 102, 'CIN', 'DET', 'tnf', '2026-08-13T23:00Z'),
  ('2026', 102, 'PIT', 'GB', 'tnf', '2026-08-13T23:00Z'),
  ('2026', 102, 'NE', 'IND', 'tnf', '2026-08-13T23:30Z'),
  ('2026', 102, 'LV', 'ARI', 'tnf', '2026-08-14T00:00Z'),
  ('2026', 102, 'HOU', 'LAC', 'tnf', '2026-08-14T00:00Z'),
  ('2026', 102, 'SF', 'TEN', 'tnf2', '2026-08-14T01:00Z'),
  ('2026', 102, 'ATL', 'DEN', 'fri', '2026-08-14T23:00Z'),
  ('2026', 102, 'NYJ', 'TB', 'fri', '2026-08-14T23:00Z'),
  ('2026', 102, 'WAS', 'MIA', 'fri', '2026-08-14T23:00Z'),
  ('2026', 102, 'BUF', 'CAR', 'sat', '2026-08-15T17:00Z'),
  ('2026', 102, 'CHI', 'CLE', 'sat', '2026-08-15T17:00Z'),
  ('2026', 102, 'NYG', 'MIN', 'sat', '2026-08-15T17:00Z'),
  ('2026', 102, 'KC', 'LA', 'sat2', '2026-08-15T20:00Z'),
  ('2026', 102, 'NO', 'JAX', 'sat2', '2026-08-15T20:00Z'),
  ('2026', 102, 'BAL', 'PHI', 'sat3', '2026-08-15T23:00Z'),
  ('2026', 102, 'SEA', 'DAL', 'sat3', '2026-08-16T00:00Z'),
  ('2026', 103, 'HOU', 'LV', 'tnf', '2026-08-21T00:00Z'),
  ('2026', 103, 'LAC', 'SF', 'tnf2', '2026-08-21T02:00Z'),
  ('2026', 103, 'PIT', 'NYJ', 'fri', '2026-08-21T23:00Z'),
  ('2026', 103, 'JAX', 'CAR', 'fri', '2026-08-21T23:30Z'),
  ('2026', 103, 'DEN', 'GB', 'fri2', '2026-08-22T01:00Z'),
  ('2026', 103, 'DET', 'WAS', 'sat', '2026-08-22T16:00Z'),
  ('2026', 103, 'CLE', 'BUF', 'sat', '2026-08-22T17:00Z'),
  ('2026', 103, 'IND', 'ATL', 'sat', '2026-08-22T17:00Z'),
  ('2026', 103, 'MIN', 'BAL', 'sat', '2026-08-22T17:00Z'),
  ('2026', 103, 'LA', 'NO', 'sat2', '2026-08-22T20:00Z'),
  ('2026', 103, 'MIA', 'NYG', 'sat2', '2026-08-22T20:00Z'),
  ('2026', 103, 'CIN', 'CHI', 'sat3', '2026-08-22T23:00Z'),
  ('2026', 103, 'NE', 'PHI', 'sat3', '2026-08-22T23:00Z'),
  ('2026', 103, 'TB', 'KC', 'sat3', '2026-08-22T23:30Z'),
  ('2026', 103, 'ARI', 'DAL', 'sat4', '2026-08-23T02:00Z'),
  ('2026', 103, 'TEN', 'SEA', 'snf', '2026-08-24T00:00Z')
on conflict (season, week, home) do update set away = excluded.away, win = excluded.win, kickoff = excluded.kickoff;
