-- 0236: THE MARKET BREATHES — a refreshable board behind player_market_value.
--
-- Founder: "Do we regularly adjust the market prices for contracts? Seems
-- like that's a thing that could fluctuate." → "Let's do a regular cosmetic
-- pull." Until now the per-player market (the cap sheet's mkt column, the
-- 85% extension base) read league_pool.rank — stamped at seed time and
-- frozen for the league's life, so a August board priced March extensions.
--
-- market_board is one global rank table, refreshed from Stathead's dynasty
-- market (the value that updates year-round; ADP goes quiet after draft
-- season, and a multi-year contract is a multi-year asset, so dynasty value
-- is the honest market for any contract league). player_market_value now
-- prefers the board's rank and falls back to the frozen pool rank for
-- anyone the board doesn't carry — probe fixtures and deep pool players
-- keep their draft-day curve. The tag market (contract_market_value,
-- top-5 positional salaries) is computed live from the league's own deals
-- and needs no refresh.
--
-- In-season the moving number is cosmetic (nothing prices off it while
-- extensions/tags/RFA are shut); at the offseason window it is exactly the
-- refresh the founder wanted extensions to price from.
--
-- REFRESH FLOW (regular — a weekly Routine drives it): rebake dyn2026.ts
-- from the Stathead MCP as usual, then
--   python3 scripts/db/gen-market-board.py
-- and file its output as a new data migration. Upserts land on this table;
-- migrate.yml applies it on merge, and every league's mkt moves that day.
--
-- LINEAGE: player_market_value patched from its 0230 body (one coalesce —
-- board rank first, pool rank as the fallback).

create table if not exists market_board (
  slug       text primary key,
  rank       int  not null check (rank >= 1),   -- 1 = most valuable, league_pool.rank's scale
  updated_at timestamptz not null default now()
);
grant select on market_board to authenticated, anon;
alter table market_board enable row level security;
drop policy if exists market_board_read on market_board;
-- Public reference data (like the pool's ranks, minus any league): open
-- read, and no write policy at all — refreshes land as migrations.
create policy market_board_read on market_board for select using (true);

create or replace function player_market_value(p_league_id uuid, p_slug text) returns int
  language sql stable security definer set search_path = public as $$
  select greatest(1, round(
    league_salary_cap(p_league_id) * 0.34 * exp(-coalesce(
      (select mb.rank from market_board mb where mb.slug = p_slug),
      (select lp.rank from league_pool lp
       where lp.league_id = p_league_id and lp.slug = p_slug)) / 45.0))::int);
$$;

-- ── first refresh, baked at ship time ────────────────────────────────────────
-- market_board refresh — Stathead dynasty market as of 2026-08-23, 464 players (1QB value order)
insert into market_board (slug, rank) values
  ('jahmyr-gibbs', 1),
  ('bijan-robinson', 2),
  ('jamarr-chase', 3),
  ('jaxon-smith-njigba', 4),
  ('puka-nacua', 5),
  ('amon-ra-st-brown', 6),
  ('ashton-jeanty', 7),
  ('jeremiyah-love', 8),
  ('brock-bowers', 9),
  ('justin-jefferson', 10),
  ('devon-achane', 11),
  ('malik-nabers', 12),
  ('omarion-hampton', 13),
  ('ceedee-lamb', 14),
  ('jonathan-taylor', 15),
  ('james-cook', 16),
  ('trey-mcbride', 17),
  ('josh-allen', 18),
  ('drake-london', 19),
  ('george-pickens', 20),
  ('chase-brown', 21),
  ('christian-mccaffrey', 22),
  ('colston-loveland', 23),
  ('tetairoa-mcmillan', 24),
  ('kenneth-walker', 25),
  ('nico-collins', 26),
  ('drake-maye', 27),
  ('saquon-barkley', 28),
  ('emeka-egbuka', 29),
  ('carnell-tate', 30),
  ('chris-olave', 31),
  ('aj-brown', 32),
  ('tyler-warren', 33),
  ('ladd-mcconkey', 34),
  ('garrett-wilson', 35),
  ('lamar-jackson', 36),
  ('quinshon-judkins', 37),
  ('breece-hall', 38),
  ('zay-flowers', 39),
  ('kyren-williams', 40),
  ('devonta-smith', 41),
  ('caleb-williams', 42),
  ('jayden-daniels', 43),
  ('luther-burden', 44),
  ('treveyon-henderson', 45),
  ('jadarian-price', 46),
  ('joe-burrow', 47),
  ('rashee-rice', 48),
  ('jordyn-tyson', 49),
  ('tee-higgins', 50),
  ('cam-skattebo', 51),
  ('javonte-williams', 52),
  ('bucky-irving', 53),
  ('jaylen-waddle', 54),
  ('derrick-henry', 55),
  ('rome-odunze', 56),
  ('makai-lemon', 57),
  ('justin-herbert', 58),
  ('tucker-kraft', 59),
  ('marvin-harrison', 60),
  ('josh-jacobs', 61),
  ('travis-etienne', 62),
  ('jalen-hurts', 63),
  ('brian-thomas', 64),
  ('jameson-williams', 65),
  ('patrick-mahomes', 66),
  ('harold-fannin', 67),
  ('bhayshul-tuten', 68),
  ('sam-laporta', 69),
  ('jaxson-dart', 70),
  ('kc-concepcion', 71),
  ('kyle-pitts', 72),
  ('trevor-lawrence', 73),
  ('bo-nix', 74),
  ('dandre-swift', 75),
  ('parker-washington', 76),
  ('david-montgomery', 77),
  ('dj-moore', 78),
  ('kenyon-sadiq', 79),
  ('dezhaun-stribling', 80),
  ('brock-purdy', 81),
  ('fernando-mendoza', 82),
  ('jonathon-brooks', 83),
  ('jordan-love', 84),
  ('dak-prescott', 85),
  ('davante-adams', 86),
  ('denzel-boston', 87),
  ('jaylen-warren', 88),
  ('christian-watson', 89),
  ('rj-harvey', 90),
  ('terry-mclaurin', 91),
  ('michael-wilson', 92),
  ('jordan-addison', 93),
  ('blake-corum', 94),
  ('george-kittle', 95),
  ('matthew-golden', 96),
  ('jonah-coleman', 97),
  ('dk-metcalf', 98),
  ('jared-goff', 99),
  ('josh-downs', 100),
  ('alec-pierce', 101),
  ('isaiah-likely', 102),
  ('jacory-croskey-merritt', 103),
  ('cam-ward', 104),
  ('chuba-hubbard', 105),
  ('quentin-johnston', 106),
  ('mike-evans', 107),
  ('wandale-robinson', 108),
  ('tyler-shough', 109),
  ('kyle-monangai', 110),
  ('jakobi-lane', 111),
  ('dalton-kincaid', 112),
  ('michael-pittman', 113),
  ('rico-dowdle', 114),
  ('zach-charbonnet', 115),
  ('eli-stowers', 116),
  ('omar-cooper', 117),
  ('baker-mayfield', 118),
  ('rhamondre-stevenson', 119),
  ('jordan-mason', 120),
  ('jayden-reed', 121),
  ('cj-stroud', 122),
  ('travis-hunter', 123),
  ('jayden-higgins', 124),
  ('nicholas-singleton', 125),
  ('xavier-worthy', 126),
  ('tony-pollard', 127),
  ('mike-washington', 128),
  ('tyler-allgeier', 129),
  ('chris-godwin', 130),
  ('jk-dobbins', 131),
  ('kenneth-gainwell', 132),
  ('jake-ferguson', 133),
  ('woody-marks', 134),
  ('romeo-doubs', 135),
  ('kyler-murray', 136),
  ('rachaad-white', 137),
  ('jalen-coker', 138),
  ('matthew-stafford', 139),
  ('cyrus-allen', 140),
  ('courtland-sutton', 141),
  ('sam-darnold', 142),
  ('travis-kelce', 143),
  ('pat-bryant', 144),
  ('tank-dell', 145),
  ('kaelon-black', 146),
  ('malachi-fields', 147),
  ('oronde-gadsden', 148),
  ('stefon-diggs', 149),
  ('terrance-ferguson', 150),
  ('tank-bigsby', 151),
  ('ricky-pearsall', 152),
  ('mark-andrews', 153),
  ('bryce-young', 154),
  ('dylan-sampson', 155),
  ('chris-rodriguez', 156),
  ('antonio-williams', 157),
  ('khalil-shakir', 158),
  ('keaton-mitchell', 159),
  ('malik-willis', 160),
  ('chris-bell', 161),
  ('tre-harris', 162),
  ('jalen-mcmillan', 163),
  ('brenton-strange', 164),
  ('braelon-allen', 165),
  ('marshawn-lloyd', 166),
  ('jakobi-meyers', 167),
  ('daniel-jones', 168),
  ('rashid-shaheed', 169),
  ('tj-hockenson', 170),
  ('aj-barner', 171),
  ('tyjae-spears', 172),
  ('jalen-nailor', 173),
  ('dallas-goedert', 174),
  ('deebo-samuel', 175),
  ('gunnar-helm', 176),
  ('juwan-johnson', 177),
  ('caleb-douglas', 178),
  ('ty-simpson', 179),
  ('zachariah-branch', 180),
  ('brian-robinson', 181),
  ('tyrone-tracy', 182),
  ('alvin-kamara', 183),
  ('isiah-pacheco', 184),
  ('tre-tucker', 185),
  ('germie-bernard', 186),
  ('malik-washington', 187),
  ('aaron-jones', 188),
  ('adonai-mitchell', 189),
  ('dontayvion-wicks', 190),
  ('jaylin-noel', 191),
  ('dalton-schultz', 192),
  ('hunter-henry', 193),
  ('ted-hurst', 194),
  ('emmett-johnson', 195),
  ('isaac-teslaa', 196),
  ('najee-harris', 197),
  ('demond-claiborne', 198),
  ('kayshon-boutte', 199),
  ('jerry-jeudy', 200),
  ('keenan-allen', 201),
  ('chig-okonkwo', 202),
  ('tory-horton', 203),
  ('kaytron-allen', 204),
  ('jaydon-blue', 205),
  ('jauan-jennings', 206),
  ('keon-coleman', 207),
  ('kaleb-johnson', 208),
  ('elijah-sarratt', 209),
  ('troy-franklin', 210),
  ('eli-raridon', 211),
  ('shedeur-sanders', 212),
  ('jack-bech', 213),
  ('kimani-vidal', 214),
  ('greg-dulcich', 215),
  ('cade-otton', 216),
  ('tua-tagovailoa', 217),
  ('carson-beck', 218),
  ('jj-mccarthy', 219),
  ('michael-penix', 220),
  ('jacoby-brissett', 221),
  ('david-njoku', 222),
  ('adam-randall', 223),
  ('tyreek-hill', 224),
  ('ollie-gordon', 225),
  ('cedric-tillman', 226),
  ('geno-smith', 227),
  ('damien-martinez', 228),
  ('elic-ayomanor', 229),
  ('joshua-palmer', 230),
  ('pat-freiermuth', 231),
  ('aaron-rodgers', 232),
  ('skyler-bell', 233),
  ('deshaun-watson', 234),
  ('ryan-flournoy', 235),
  ('brandon-aiyuk', 236),
  ('jaleel-mclaughlin', 237),
  ('michael-mayer', 238),
  ('trey-benson', 239),
  ('jerome-ford', 240),
  ('devontez-walker', 241),
  ('mason-taylor', 242),
  ('ray-davis', 243),
  ('tai-felton', 244),
  ('rasheen-ali', 245),
  ('jordan-james', 246),
  ('kirk-cousins', 247),
  ('jalin-hyatt', 248),
  ('chimere-dike', 249),
  ('raheim-sanders', 250),
  ('elijah-arroyo', 251),
  ('jaylen-wright', 252),
  ('tahj-washington', 253),
  ('max-klare', 254),
  ('elijah-moore', 255),
  ('rashod-bateman', 256),
  ('trey-palmer', 257),
  ('kyle-williams', 258),
  ('greg-dortch', 259),
  ('donovan-edwards', 260),
  ('calvin-ridley', 261),
  ('theo-johnson', 262),
  ('kalel-mullings', 263),
  ('cooper-kupp', 264),
  ('bryce-lance', 265),
  ('kendrick-bourne', 266),
  ('malachi-corley', 267),
  ('bam-knight', 268),
  ('jacob-cowing', 269),
  ('sean-tucker', 270),
  ('malik-benson', 271),
  ('kameron-johnson', 272),
  ('jake-tonges', 273),
  ('anthony-richardson', 274),
  ('chris-brazzell', 275),
  ('dj-giddens', 276),
  ('justin-joly', 277),
  ('tyler-goodson', 278),
  ('xavier-legette', 279),
  ('xavier-restrepo', 280),
  ('james-conner', 281),
  ('gabriel-davis', 282),
  ('israel-abanikanda', 283),
  ('dameon-pierce', 284),
  ('tyler-badie', 285),
  ('barion-brown', 286),
  ('cade-stover', 287),
  ('leveon-moss', 288),
  ('oscar-delp', 289),
  ('darren-waller', 290),
  ('isaiah-bond', 291),
  ('david-bell', 292),
  ('frank-gore', 293),
  ('javon-baker', 294),
  ('tommy-tremble', 295),
  ('michael-carter', 296),
  ('mac-jones', 297),
  ('kendall-milton', 298),
  ('isaiah-davis', 299),
  ('jonathan-mingo', 300),
  ('sione-vaki', 301),
  ('tyler-higbee', 302),
  ('jake-bobo', 303),
  ('tyler-scott', 304),
  ('darnell-mooney', 305),
  ('seth-mcgowan', 306),
  ('isaiah-hodgins', 307),
  ('evan-engram', 308),
  ('mack-hollins', 309),
  ('xavier-gipson', 310),
  ('devaughn-vele', 311),
  ('colby-parkinson', 312),
  ('elijah-higgins', 313),
  ('mitchell-evans', 314),
  ('zavion-thomas', 315),
  ('tyrell-shavers', 316),
  ('arian-smith', 317),
  ('emanuel-wilson', 318),
  ('bub-means', 319),
  ('luke-schoonmaker', 320),
  ('mason-tipton', 321),
  ('bo-melton', 322),
  ('reggie-virgil', 323),
  ('matthew-hibner', 324),
  ('davis-allen', 325),
  ('johnny-wilson', 326),
  ('aj-dillon', 327),
  ('cade-klubnik', 328),
  ('brevin-jordan', 329),
  ('lequint-allen', 330),
  ('hassan-haskins', 331),
  ('tez-johnson', 332),
  ('jawhar-jordan', 333),
  ('marvin-mims', 334),
  ('kevin-coleman', 335),
  ('demarcus-robinson', 336),
  ('brenen-thompson', 337),
  ('sincere-mccormick', 338),
  ('jared-wiley', 339),
  ('liljordan-humphrey', 340),
  ('nathan-carter', 341),
  ('devin-neal', 342),
  ('tyquan-thornton', 343),
  ('derius-davis', 344),
  ('george-holani', 345),
  ('alexander-mattison', 346),
  ('eli-heidenreich', 347),
  ('trayveon-williams', 348),
  ('cole-kmet', 349),
  ('ty-chandler', 350),
  ('zamir-white', 351),
  ('mecole-hardman', 352),
  ('justin-fields', 353),
  ('dylan-laube', 354),
  ('colbie-young', 355),
  ('brock-wright', 356),
  ('zavier-scott', 357),
  ('jeremy-mcnichols', 358),
  ('lajohntay-wester', 359),
  ('malik-heath', 360),
  ('demario-douglas', 361),
  ('jalen-royals', 362),
  ('marlin-klein', 363),
  ('jamari-thrash', 364),
  ('jalen-milroe', 365),
  ('justice-hill', 366),
  ('xavier-hutchinson', 367),
  ('sam-howell', 368),
  ('darnell-washington', 369),
  ('tyler-johnson', 370),
  ('tyler-huntley', 371),
  ('tylan-wallace', 372),
  ('cj-daniels', 373),
  ('zach-wilson', 374),
  ('christian-kirk', 375),
  ('jahan-dotson', 376),
  ('jatavion-sanders', 377),
  ('trevor-etienne', 378),
  ('van-jefferson', 379),
  ('donte-thornton', 380),
  ('brenden-rice', 381),
  ('tanner-koziol', 382),
  ('erick-all', 383),
  ('marquise-brown', 384),
  ('tahj-brooks', 385),
  ('tanner-mckee', 386),
  ('luke-mccaffrey', 387),
  ('will-howard', 388),
  ('hunter-long', 389),
  ('brashard-smith', 390),
  ('chris-brooks', 391),
  ('deion-burks', 392),
  ('joe-flacco', 393),
  ('drew-lock', 394),
  ('luke-musgrave', 395),
  ('andrei-iosivas', 396),
  ('jam-miller', 397),
  ('treylon-burks', 398),
  ('gardner-minshew', 399),
  ('samaje-perine', 400),
  ('jmari-taylor', 401),
  ('ben-sinnott', 402),
  ('savion-williams', 403),
  ('jarquez-hunter', 404),
  ('garrett-nussmeier', 405),
  ('calvin-austin', 406),
  ('roman-wilson', 407),
  ('jameis-winston', 408),
  ('marcus-mariota', 409),
  ('michael-trigg', 410),
  ('sam-roush', 411),
  ('malik-davis', 412),
  ('john-metchie', 413),
  ('noah-gray', 414),
  ('darius-slayton', 415),
  ('ty-johnson', 416),
  ('riley-leonard', 417),
  ('jack-endries', 418),
  ('jalen-tolbert', 419),
  ('davis-mills', 420),
  ('tyson-bagent', 421),
  ('mike-gesicki', 422),
  ('joe-milton', 423),
  ('kyle-mccord', 424),
  ('dawson-knox', 425),
  ('jaylin-lane', 426),
  ('emari-demercado', 427),
  ('kendre-miller', 428),
  ('stetson-bennett', 429),
  ('drew-allar', 430),
  ('devin-singletary', 431),
  ('tutu-atwell', 432),
  ('kavontae-turpin', 433),
  ('taylen-green', 434),
  ('cole-payton', 435),
  ('charlie-kolar', 436),
  ('will-shipley', 437),
  ('quinn-ewers', 438),
  ('spencer-rattler', 439),
  ('roschon-johnson', 440),
  ('isaac-guerendo', 441),
  ('jordan-whittington', 442),
  ('dillon-gabriel', 443),
  ('jimmy-horn', 444),
  ('jordan-watkins', 445),
  ('trey-lance', 446),
  ('kareem-hunt', 447),
  ('keandre-lambert-smith', 448),
  ('konata-mumpfield', 449),
  ('nick-westbrook-ikhine', 450),
  ('khalil-herbert', 451),
  ('dyami-brown', 452),
  ('audric-estime', 453),
  ('olamide-zaccheaus', 454),
  ('phil-mafah', 455),
  ('will-levis', 456),
  ('daniel-bellinger', 457),
  ('noah-fant', 458),
  ('jahdae-walker', 459),
  ('efton-chism', 460),
  ('skyy-moore', 461),
  ('jonnu-smith', 462),
  ('kenny-pickett', 463),
  ('noah-brown', 464)
on conflict (slug) do update set rank = excluded.rank, updated_at = now();
