-- 0428 — A SPORT LEAGUE'S SETTINGS ARE THE COMMISSIONER'S (v0.619.0).
--
-- `set_sport_settings` patches settings_json.sport: the scoring knobs
-- (stat id → points, any time — the worker rescores every live matchup on
-- its next pass), the format and categories (until the first period goes
-- live — a league that has scored a week cannot change what a week is),
-- and period_start / weeks (until any matchup is live). Values are
-- sanitised here; which stat ids and category ids exist is the SportDef's
-- business, so unknown keys are kept as given and the client offers only
-- real ones.
--
-- Undo: drop function if exists set_sport_settings(uuid, jsonb);

create or replace function set_sport_settings(p_league_id uuid, p_patch jsonb)
  returns jsonb language plpgsql security definer set search_path = public as $$
declare cur jsonb; nxt jsonb; live boolean; k text; v text; sc jsonb := '{}'::jsonb; f text; cats jsonb; ps date; wk int;
begin
  if not (is_admin() or is_league_commish(p_league_id)) then
    return jsonb_build_object('ok', false, 'error', 'forbidden');
  end if;
  if league_sport(p_league_id) = 'nfl' then
    return jsonb_build_object('ok', false, 'error', 'not a sport league');
  end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    return jsonb_build_object('ok', false, 'error', 'patch must be an object');
  end if;
  select coalesce(settings_json -> 'sport', '{}'::jsonb) into cur from league where id = p_league_id;
  nxt := cur;
  live := exists (select 1 from matchup m where m.league_id = p_league_id and m.status <> 'scheduled');

  -- scoring: finite numbers only, any time
  if p_patch ? 'scoring' then
    if jsonb_typeof(p_patch -> 'scoring') <> 'object' then
      return jsonb_build_object('ok', false, 'error', 'scoring must be an object');
    end if;
    for k, v in select * from jsonb_each_text(p_patch -> 'scoring') loop
      if v ~ '^-?\d+(\.\d+)?$' and abs(v::numeric) <= 1000 then sc := sc || jsonb_build_object(k, v::numeric); end if;
    end loop;
    nxt := nxt || jsonb_build_object('scoring', sc);
  end if;

  -- format + categories: until the season is under way
  if p_patch ? 'format' or p_patch ? 'categories' then
    if live then return jsonb_build_object('ok', false, 'error', 'the season is under way — the format and categories are locked'); end if;
    if p_patch ? 'format' then
      f := p_patch ->> 'format';
      if f not in ('points', 'cats', 'roto') then return jsonb_build_object('ok', false, 'error', 'format must be points, cats or roto'); end if;
      nxt := nxt || jsonb_build_object('format', f);
    end if;
    if p_patch ? 'categories' then
      if jsonb_typeof(p_patch -> 'categories') <> 'array' then return jsonb_build_object('ok', false, 'error', 'categories must be an array'); end if;
      select coalesce(jsonb_agg(distinct x), '[]'::jsonb) into cats
        from jsonb_array_elements_text(p_patch -> 'categories') x where x ~ '^[a-z0-9_]{1,24}$';
      if jsonb_array_length(cats) > 20 then return jsonb_build_object('ok', false, 'error', 'at most 20 categories'); end if;
      nxt := nxt || jsonb_build_object('categories', cats);
    end if;
  end if;

  -- the calendar: until any matchup is live; the schedule is regenerated by the caller
  if p_patch ? 'period_start' or p_patch ? 'weeks' then
    if live then return jsonb_build_object('ok', false, 'error', 'the season is under way — the calendar is locked'); end if;
    if p_patch ? 'period_start' then
      begin ps := (p_patch ->> 'period_start')::date; exception when others then
        return jsonb_build_object('ok', false, 'error', 'period_start must be a date'); end;
      -- always the Monday on or before
      ps := ps - ((extract(isodow from ps)::int - 1));
      nxt := nxt || jsonb_build_object('period_start', to_char(ps, 'YYYY-MM-DD'));
    end if;
    if p_patch ? 'weeks' then
      wk := (p_patch ->> 'weeks')::int;
      if wk is null or wk < 1 or wk > 30 then return jsonb_build_object('ok', false, 'error', 'weeks must be 1–30'); end if;
      nxt := nxt || jsonb_build_object('weeks', wk);
    end if;
  end if;

  update league set settings_json = coalesce(settings_json, '{}'::jsonb) || jsonb_build_object('sport', nxt) where id = p_league_id;
  return jsonb_build_object('ok', true, 'sport', nxt);
end $$;
grant execute on function set_sport_settings(uuid, jsonb) to authenticated;
