// Expo config plugin: sign release builds with the playtest key instead of the
// public Android debug key.
//
// WHAT IT REPLACES: the bare template wires `release { signingConfig
// signingConfigs.debug }` — and that debug key is not a per-machine key, it's
// the fixed `debug.keystore` the template ships, dated 2013, with the
// SHA256 FA:C6:17:45… that every React Native project on earth carries.
// Builds signed with it install fine, so nothing looks wrong; the problems are
// that anyone can forge an update for com.dripfantasy.app, and Play will never
// accept that identity. Playtesters sideloading from a link deserve better than
// a key whose private half is on GitHub.
//
// WHY A PLUGIN AND NOT AN EDIT TO android/app/build.gradle: `android/` is
// generated by `expo prebuild` and gitignored, so an edit there is untracked
// and dies at the next `prebuild --clean`. Same reasoning as
// withCoreBundleInput.js — see its header.
//
// ABOUT THE COMMITTED KEYSTORE AND ITS PASSWORD: `playtest.keystore` is in the
// repo and the password is right here in the source. That is deliberate, and it
// is only defensible because of what this key is NOT:
//
//   · It is not the Play Store upload key. When this ships, generate a fresh
//     key, hand it to EAS credentials (or Play App Signing), and leave this one
//     to sideloaded builds. Play App Signing also makes the upload key
//     rotatable, so choosing a real key later costs nothing today.
//   · It guards nothing on the server. Every table is RLS-guarded against the
//     signed-in user; a forged build gets you a login screen.
//
// What it buys is that Drip's sideloaded builds have their own identity rather
// than sharing one with the entire RN ecosystem, and that identity is stable —
// so a playtester's next APK installs over the last one instead of demanding an
// uninstall. Keeping it in the repo is what makes it stable across a fresh
// clone or a throwaway CI container. If that trade ever stops being worth it,
// move the file out and pass the path in through the environment; the assertion
// below will tell you loudly when it goes missing rather than silently falling
// back to the debug key.
const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = 'dripPlaytestSigning';

// Relative to android/app/, where build.gradle lives: `..` is android/,
// `../..` is apps/mobile/. Resolved at Gradle configuration time, so this works
// the same for a local `assembleRelease` and for an EAS build that uploaded the
// project directory.
const KEYSTORE = '../../playtest.keystore';
const STORE_PASSWORD = 'dripplaytest';
const KEY_ALIAS = 'playtest';

const BLOCK = `
// ── Playtest release signing ──────────────────────────────────────────────────
// Generated by apps/mobile/plugins/withPlaytestSigning.js — edit that, not this.
// The template signs release with the PUBLIC debug key; this replaces it.
def dripPlaytestStore = file('${KEYSTORE}')
if (!dripPlaytestStore.exists()) {
    throw new GradleException(
        "playtest.keystore not found at \${dripPlaytestStore}. Release builds " +
        "would silently fall back to the public Android debug key, which is " +
        "not a signing identity. Restore the file rather than removing this check.")
}
android {
    signingConfigs {
        ${MARKER} {
            storeFile dripPlaytestStore
            storePassword '${STORE_PASSWORD}'
            keyAlias '${KEY_ALIAS}'
            keyPassword '${STORE_PASSWORD}'
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.${MARKER}
        }
    }
}
`;

module.exports = function withPlaytestSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withPlaytestSigning: expected a Groovy build.gradle');
    }
    // Idempotent: prebuild can run repeatedly against an existing file.
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += BLOCK;
    }
    return cfg;
  });
};
