// Expo config plugin: turn on R8 + resource shrinking for release builds.
//
// WHY: the release APK is mostly Dalvik bytecode — 19.7 MB uncompressed across
// three .dex files against 17.9 MB of native libs — and none of it was being
// shrunk, because the Expo template defaults `android.enableMinifyInReleaseBuilds`
// to false. React Native and Expo both ship consumer ProGuard rules for their own
// reflection, which is what makes this a supported switch rather than a gamble.
//
// WHY A PLUGIN: `android/gradle.properties` is generated by `expo prebuild` and
// gitignored, so setting this by hand there survives exactly until the next
// `prebuild --clean`. Same reasoning as withCoreBundleInput and
// withPlaytestSigning — see their headers.
//
// WHAT TO WATCH: R8 removes code it cannot see being used, and it cannot see
// reflection. Anything reached only by name — a native module looked up by
// string, a JSON payload deserialized into a class — can vanish and the build
// will still succeed. That failure appears at RUNTIME, on a screen nobody
// opened during the build, which is why a shrunk build deserves a pass through
// every screen rather than a glance at the home page. If something does break,
// the fix is a `-keep` rule in android/app/proguard-rules.pro (which is itself
// generated — so it would need its own plugin, or this one extended).
const { withGradleProperties } = require('@expo/config-plugins');

const PROPS = {
  // R8: shrink, optimise and obfuscate the dex.
  'android.enableMinifyInReleaseBuilds': 'true',
  // Drop resources nothing references. Gated on minify by AGP, so it only does
  // anything alongside the flag above.
  'android.enableShrinkResourcesInReleaseBuilds': 'true',
};

module.exports = function withReleaseShrink(config) {
  return withGradleProperties(config, (cfg) => {
    for (const [key, value] of Object.entries(PROPS)) {
      const existing = cfg.modResults.find((i) => i.type === 'property' && i.key === key);
      // Idempotent, and an explicit overwrite rather than a push: prebuild can
      // run against an existing file, and the template may already carry the
      // key set to false.
      if (existing) existing.value = value;
      else cfg.modResults.push({ type: 'property', key, value });
    }
    return cfg;
  });
};
