// Expo config plugin: adopt the UIKit SCENE life cycle on iOS.
//
// WHY: apps built with the iOS 27 SDK (Xcode 27) refuse to launch without it —
// the build succeeds, then the Simulator logs "UIScene life cycle is required
// for apps built with this SDK" and the app never opens. SDK 58's project
// template adopts scenes; SDK 57's (which `expo prebuild` generates for us)
// does not. The runtime half already shipped in expo 57.0.25:
// `ExpoAppSceneDelegate` creates the window, starts React Native in it, and
// re-feeds URLs / user activities / life-cycle events to the app delegate —
// written to work with SDK 57 app delegates, including their own
// RCTLinkingManager calls (it dedupes). So this plugin only has to do what the
// SDK 58 template does to the generated files:
//
//   1. Info.plist — a UIApplicationSceneManifest naming SceneDelegate.
//   2. SceneDelegate.swift — an empty subclass of ExpoAppSceneDelegate, added
//      to the Xcode target.
//   3. AppDelegate.swift — conform to ExpoReactNativeFactoryProvider (how the
//      scene delegate finds the factory) and stop creating the window and
//      starting React Native itself; the scene delegate does both.
//
// WHY A PLUGIN: `ios/` is generated and gitignored, same as `android/` — see
// withCoreBundleInput. DELETE THIS when the app moves to SDK 58: its template
// does all three, and step 3's pattern will no longer match (the plugin throws
// rather than silently doing nothing, so that will be noticed).
const fs = require('fs');
const path = require('path');
const { withAppDelegate, withInfoPlist, withXcodeProject, IOSConfig } = require('@expo/config-plugins');

const SCENE_DELEGATE = `internal import Expo

// Generated by plugins/withSceneLifecycle.js — see its header.
@objc(SceneDelegate)
class SceneDelegate: ExpoAppSceneDelegate {
  // Extension point for config plugins.
}
`;

function withScenePlist(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });
}

function withSceneAppDelegate(config) {
  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error('withSceneLifecycle: expected a Swift AppDelegate.');
    }
    let src = cfg.modResults.contents;
    if (!src.includes('ExpoReactNativeFactoryProvider')) {
      const decl = 'class AppDelegate: ExpoAppDelegate {';
      if (!src.includes(decl)) throw new Error('withSceneLifecycle: AppDelegate declaration not found — has the template changed (SDK 58 adopts scenes itself)?');
      src = src.replace(decl, 'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {');
    }
    // The window + startReactNative block. Under scenes the app delegate has
    // no window to start into; leaving it would start React Native twice.
    const start = /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n[\s\S]*?#endif\n/;
    if (start.test(src)) {
      src = src.replace(start, '    // The window is created and React Native started by SceneDelegate (plugins/withSceneLifecycle.js).\n');
    } else if (!src.includes('started by SceneDelegate')) {
      throw new Error('withSceneLifecycle: window/startReactNative block not found in AppDelegate.swift.');
    }
    cfg.modResults.contents = src;
    return cfg;
  });
}

function withSceneDelegateFile(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const name = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
    const file = path.join(cfg.modRequest.platformProjectRoot, name, 'SceneDelegate.swift');
    fs.writeFileSync(file, SCENE_DELEGATE);
    const rel = `${name}/SceneDelegate.swift`;
    if (!project.hasFile(rel)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({ filepath: rel, groupName: name, project });
    }
    return cfg;
  });
}

module.exports = function withSceneLifecycle(config) {
  return withSceneDelegateFile(withSceneAppDelegate(withScenePlist(config)));
};
