// Real 2025 play-by-play, loaded per-week on demand so it stays out of the main
// bundle. Each week's data lives in public/pbp/w{N}.json (generated by
// scripts/pbp/genRealPbp.mjs) and is fetched + cached the first time that week
// is viewed. Until a week is loaded, the accessors report "no data" and the
// engine falls back to its deterministic simulation.
import { REAL_WEEKS } from './realWeeks';

export { REAL_WEEKS };
export type RealPlayKind =
  | 'pass' | 'rush' | 'rec' | 'incomplete'      // skill
  | 'return'                                     // kick/punt return yards
  | 'fg' | 'fgmiss' | 'xp' | 'xpmiss'           // kicker
  | 'sack' | 'int' | 'fumrec' | 'dst_td' | 'safety'  // team defense
  | 'tackle';                                        // IDP (individual defender)
// `c` is the game-elapsed clock (seconds). `t` is the REAL wall-clock time of
// the play, in seconds since the game's first snap (baked from nflverse
// time_of_day) — used to gate real-time power-ups so a delayed feed can't be
// exploited. `pid` is the nflverse play_id (stable per-game key, for future
// live-feed gating). `t`/`pid` are optional: data baked before real-time
// support, return plays, and synthesized data omit them and callers fall back.
export interface RealPlay { c: number; t?: number; pid?: number; k: RealPlayKind; y: number; td: number; ca: number; tg: number; to?: number; }

interface WeekData { pbp: Record<string, RealPlay[]>; points: Record<string, number>; poss?: Record<string, number[][]>; wall?: Record<string, number[]>; ends?: Record<string, number>; kick?: Record<string, number>; }

const cache = new Map<number, WeekData>();
const inflight = new Map<number, Promise<void>>();

// ── Synthetic overlay (runtime) ──────────────────────────────────────────────
// When a live Sleeper league is loaded, players we DON'T have baked play-by-play
// for get a synthesized timeline scaled to their real weekly Sleeper total (see
// data/buildLeague.ts). Baked data always wins; the overlay only fills the gaps.
const synthPbp = new Map<number, Record<string, RealPlay[]>>();
const synthPts = new Map<number, Record<string, number>>();

/** Install synthesized per-week play-by-play + points for the active league. */
export function setSyntheticWeeks(weeks: { week: number; pbp: Record<string, RealPlay[]>; points: Record<string, number> }[]): void {
  synthPbp.clear(); synthPts.clear();
  for (const w of weeks) { synthPbp.set(w.week, w.pbp); synthPts.set(w.week, w.points); }
}
/** Drop all synthesized data (back to the baked demo league). */
export function clearSyntheticWeeks(): void { synthPbp.clear(); synthPts.clear(); }

// ── Live overlay (worker-ingested plays) ─────────────────────────────────────
// For a real pilot matchup, the worker's live_play rows for the week are installed
// here. A live week resolves ONLY from these (baked + synth suppressed) so the
// board shows the actual game: no play yet = DNP 0, scores accrue as plays ingest.
const livePbp = new Map<number, Record<string, RealPlay[]>>();
const livePts = new Map<number, Record<string, number>>();
/** Install the week's live (worker) play-by-play; makes that week resolve live. */
export function setLivePlays(week: number, pbp: Record<string, RealPlay[]>, points: Record<string, number> = {}): void {
  livePbp.set(week, pbp); livePts.set(week, points);
}
/** Drop all live overlays (back to baked/synth resolution). */
export function clearLivePlays(): void { livePbp.clear(); livePts.clear(); }

/** live_play DB rows → {slug: RealPlay[]} (mirrors the worker's rowsToPbp). */
export function liveRowsToPbp(rows: { player_slug: string; c: number; t: number | null; pid: number | null; k: string; y: number; td: number; ca: number; tg: number; to: number | null }[]): Record<string, RealPlay[]> {
  const by: Record<string, RealPlay[]> = {};
  for (const r of rows) (by[r.player_slug] ||= []).push({ c: r.c, t: r.t ?? undefined, pid: r.pid ?? undefined, k: r.k as RealPlayKind, y: r.y, td: r.td, ca: r.ca, tg: r.tg, ...(r.to ? { to: r.to } : {}) });
  for (const s of Object.keys(by)) by[s].sort((a, b) => a.c - b.c);
  return by;
}


/** True once a real week's baked JSON has been fetched into the cache. NOTE:
 *  this gates the per-week fetch, so it must reflect ONLY the baked cache — the
 *  synthetic overlay is in-memory and supplements it, but the baked w*.json must
 *  still be fetched (it carries every baked player plus per-team poss/wall data). */
export function isRealWeekLoaded(week: number): boolean {
  return cache.has(week);
}

/** Fetch + cache a week's real play-by-play (no-op if not a real week or already loaded). */
export function loadRealWeek(week: number): Promise<void> {
  if (!REAL_WEEKS.has(week) || cache.has(week)) return Promise.resolve();
  let p = inflight.get(week);
  if (!p) {
    const url = `${import.meta.env.BASE_URL}pbp/w${week}.json`;
    p = fetch(url)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`pbp w${week}: HTTP ${r.status}`))))
      .then((data: WeekData) => { cache.set(week, data); })
      .catch((e) => { console.error('[realPbp] load failed', e); /* leave uncached → sim fallback */ })
      .finally(() => { inflight.delete(week); });
    inflight.set(week, p);
  }
  return p;
}

/** Per-player real fantasy points for a loaded week ({} if not loaded). Baked
 *  totals win; synthesized totals fill in players we didn't bake. */
export function realPointsFor(week: number): Record<string, number> {
  if (livePbp.has(week)) return livePts.get(week) ?? {}; // live week: only live points
  const synth = synthPts.get(week);
  const baked = cache.get(week)?.points;
  if (synth && baked) return { ...synth, ...baked };
  return baked ?? synth ?? {};
}

/** Real plays for a player in a loaded week, or null (→ DNP/sim per phase).
 *  Live overlay wins and is exclusive (a live week ignores baked/synth, so a
 *  player with no live play yet reads as 0); else baked PBP, then synth. */
export function realPbpFor(week: number, playerId: string): RealPlay[] | null {
  const live = livePbp.get(week);
  if (live) { const lp = live[playerId]; return lp && lp.length ? lp : null; }
  const ps = cache.get(week)?.pbp[playerId];
  if (ps && ps.length) return ps;
  const sp = synthPbp.get(week)?.[playerId];
  return sp && sp.length ? sp : null;
}

/** A team's offensive possession intervals [startSec,endSec] for a loaded week
 *  (for the possession-gated WR drip); empty if not loaded/known. */
export function realPossFor(week: number, team: string): number[][] {
  return cache.get(week)?.poss?.[team] ?? [];
}

/** A team's real game end clock (max game-elapsed second, including overtime)
 *  for a loaded week, or 0 if not loaded/known. */
export function realGameEndClock(week: number, team: string): number {
  return cache.get(week)?.ends?.[team] ?? 0;
}

/** A team's real kickoff (first snap, floored to 5 min) as epoch ms for a loaded
 *  week, or null if not loaded/known. */
export function realKickoff(week: number, team: string): number | null {
  return cache.get(week)?.kick?.[team] ?? null;
}

/** A game's ACTIVE-WALL timeline (cumulative real wall-seconds in play, breaks
 *  excluded), sampled per game-minute — index i = game clock i·60. Looked up by
 *  either team of the game; null if not loaded/known. Drives REAL CLOCK drip. */
export function realWallFor(week: number, team: string): number[] | null {
  return cache.get(week)?.wall?.[team] ?? null;
}
