// AUTO-GENERATED by scripts/pbp/genRealPbp.mjs — do not edit by hand.
// Weeks with baked real 2025 play-by-play (per-week JSON in public/pbp/wN.json).
export const REAL_WEEKS = new Set<number>([1, 2, 3, 4, 5, 6, 7, 8, 9]);
