// AUTO-GENERATED by scripts/pbp/genRealPbp.mjs — do not edit by hand.
// Weeks with baked real 2025 play-by-play (per-week JSON in public/pbp/wN.json).
export const REAL_WEEKS = new Set<number>([]);
