// Real 2025 play-by-play, loaded per-week on demand so it stays out of the main
// bundle. Each week's data lives in public/pbp/w{N}.json (generated by
// scripts/pbp/genRealPbp.mjs) and is fetched + cached the first time that week
// is viewed. Until a week is loaded, the accessors report "no data" and the
// engine falls back to its deterministic simulation.
import { REAL_WEEKS } from './realWeeks';

export { REAL_WEEKS };
export interface RealPlay { c: number; k: 'pass' | 'rush' | 'rec' | 'incomplete'; y: number; td: number; ca: number; tg: number; }

interface WeekData { pbp: Record<string, RealPlay[]>; points: Record<string, number>; }

const cache = new Map<number, WeekData>();
const inflight = new Map<number, Promise<void>>();

/** True once a real week's JSON has been fetched into the cache. */
export function isRealWeekLoaded(week: number): boolean {
  return cache.has(week);
}

/** Fetch + cache a week's real play-by-play (no-op if not a real week or already loaded). */
export function loadRealWeek(week: number): Promise<void> {
  if (!REAL_WEEKS.has(week) || cache.has(week)) return Promise.resolve();
  let p = inflight.get(week);
  if (!p) {
    const url = `${import.meta.env.BASE_URL}pbp/w${week}.json`;
    p = fetch(url)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`pbp w${week}: HTTP ${r.status}`))))
      .then((data: WeekData) => { cache.set(week, data); })
      .catch((e) => { console.error('[realPbp] load failed', e); /* leave uncached → sim fallback */ })
      .finally(() => { inflight.delete(week); });
    inflight.set(week, p);
  }
  return p;
}

/** Per-player real fantasy points for a loaded week ({} if not loaded). */
export function realPointsFor(week: number): Record<string, number> {
  return cache.get(week)?.points ?? {};
}

/** Real plays for a player in a loaded week, or null (→ engine simulates). */
export function realPbpFor(week: number, playerId: string): RealPlay[] | null {
  const ps = cache.get(week)?.pbp[playerId];
  return ps && ps.length ? ps : null;
}
